# -*- coding: utf-8 -*-
from build_house import race, c, write
from gen_thin import thin

race(1, "U.S. House — Michigan District 1",
 "All 15 Upper Peninsula counties plus 20 in the northern Lower Peninsula — Traverse City, Marquette, Alpena, Sault Ste. Marie",
 "BERGMAN TOOK 74.3% OF A THREE-WAY PRIMARY — BUT FOUR OF HIS OWN REGION'S REPUBLICAN LEGISLATORS HAD PULLED THEIR ENDORSEMENTS IN FEBRUARY. State Reps. Bohnak, Markkanen, McBroom and Prestin rescinded over a state Senate dispute; he won anyway. ⚠ Challenger Matthew DenOtter SELF-FUNDED $1,877,175 of his $1,906,389 — nearly matching Bergman's entire raise — and took 13.1%. Callie Barr won the Democratic primary with 58.5% and is running a rematch of 2024. Cook PVI R+11; Solid or Safe R at all three raters. Official Secretary of State results: Bergman 80,726 (74.33%), DenOtter 14,254, Justin Michal 13,627; Barr 62,197 (58.49%), Kyle Blomquist 37,936, Wayne Stiles 6,213.",
 [c("Jack Bergman (incumbent)", "R",
    ["Secure the border and enforce immigration law",
     "Strengthen national defense and veterans' services",
     "Rein in federal spending"],
    ["Retired U.S. Marine Corps lieutenant general; in Congress since 2017",
     "Rural broadband is his signature local bill — H.R.4905 and H.R.1610",
     "$1,917,574 raised, $660,163 on hand (FEC, July 15, 2026)",
     "Endorsed by Trump (Nov 1, 2025) and AIPAC"],
    ["Delivers concrete federal money to a vast rural district — broadband, the Soo Locks, VA services",
     "Rank and seniority give the Upper Peninsula reach it would not otherwise have",
     "Holds Trump's endorsement in an R+11 seat"],
    ["Four Upper Peninsula Republican legislators publicly rescinded their endorsements in February 2026",
     "At 78 he is the oldest member of Michigan's delegation — Cook's own race summary says so",
     "Barr's campaign frames him as absent, running on 'the places Jack Bergman forgets'"]),
  c("Callie Barr", "D",
    ["Federal funding for local homebuilding, zoning reform and limits on short-term rentals",
     "PRO Act, protect Social Security and remove the payroll cap",
     "Protect Medicaid and rural hospitals; extend ACA subsidies plus a public option"],
    ["Attorney and former high-school teacher from Traverse City",
     "The 2024 nominee for this seat — this is a rematch",
     "Became her Marine husband's caretaker, then a veterans' advocate",
     "$824,340 raised, $530,724 on hand (FEC, July 15, 2026)",
     "Endorsed by Pete Buttigieg, former Rep. Bart Stupak, EMILYs List and VoteVets"],
    ["Consolidated the primary at 58% and has the strongest cash position of any recent MI-1 Democrat",
     "Her affordability and rural-hospital message is aimed at the district's actual economics",
     "National women's and veterans' groups moved in immediately after the primary"],
    ["She lost this district in 2024 and faces the same R+11 arithmetic",
     "Trails Bergman better than two to one in money raised",
     "All three raters call the seat Solid or Safe R, so outside money is unlikely to arrive [Verify — structural argument]"]),
  thin("Arnett Satterla", "L"),
  thin("Doc Kovaly", "UST"),
  thin("LaVeta Davenport", "G"),
  thin("Liz Hakola", "WCP",
       extra_diff="Also the Working Class nominee here in 2022 and 2024",
       extra_sup="A third consecutive run gives her the most name recognition in the minor-party field here [Verify — structural argument]",
       extra_opp="She did not win in 2022 or 2024 and no campaign operation could be located this cycle [Verify — an absence of located records]"),
  thin("Zebulon Featherly", "NPA",
       extra_diff="Qualified with No Party Affiliation — the only true independent on the MI-1 ballot")])

race(2, "U.S. House — Michigan District 2",
 "West-central Michigan, 20 counties — Mount Pleasant, Big Rapids, Manistee, Ionia, plus slivers of Kent, Ottawa and Midland",
 "THE CLOSEST PRIMARY IN THE STATE: BEN AMBROSE WON THE DEMOCRATIC NOMINATION BY 1,497 VOTES, 2.04 POINTS, and AP did not call it until 4:36 p.m. the next day. ⚠ Not an upset — Ambrose held the Detroit News endorsement — but a near-miss that leaves him without a unified party. Moolenaar was unopposed. Official Secretary of State results: Moolenaar 93,751 (100%); Ambrose 32,445 (44.32%), Jamie Hill 30,948 (42.28%), Clyde Welford 9,806 (13.40%). Cook PVI R+15, the most Republican seat in the state; Solid or Safe R at all three raters. ⚠ EASY TO MISS: Natural Law nominee Richard Sills filed by convention on SEPT 1, 2026, after most voter guides were built — Michigan Advance's guide lists only the Green.",
 [c("John Moolenaar (incumbent)", "R",
    ["Secure the border",
     "Cut wasteful federal spending and rebuild the military",
     "Counter the Chinese Communist Party — block foreign purchases of American farmland"],
    ["In Congress since 2015; previously served in both chambers of the Michigan Legislature",
     "Chair of the House Select Committee on the CCP and a member of Appropriations",
     "$1,652,234 raised but $1,905,561 on hand — carryover leaves him with more banked than he raised (FEC, July 15, 2026)",
     "Endorsed by Trump and AIPAC"],
    ["A national committee chairmanship brings the district influence far above a backbencher's",
     "An appropriator who can direct federal money home",
     "Cleared the primary unopposed in an R+15 seat"],
    ["Cook's own public summary calls him a 64-year-old appropriator who keeps a low profile and will have no trouble winning re-election",
     "The China chairmanship draws attention away from local constituent work — the implicit contrast in Ambrose's framing [Verify — structural argument]",
     "An R+15 seat means he faces little electoral scrutiny in any given cycle [Verify — structural argument]"]),
  c("Ben Ambrose", "D",
    ["Affordability and expanding job opportunities",
     "Michigan's K-12 and higher-education systems",
     "Medicare for All"],
    ["Grew up on a small farm in Hesperia; nearly 20 years in the U.S. Marine Corps with multiple combat tours",
     "Later a staffer to Sen. Ron Wyden (D-OR); MBA from Johns Hopkins, master's from Harvard",
     "$85,093 raised, $21,867 on hand (FEC, July 15, 2026)",
     "Detroit News primary endorsement and UFCW Local 951"],
    ["A Marine combat veteran with a farm-country biography is the strongest profile Democrats have fielded here recently",
     "The Detroit News endorsed him over two rivals",
     "Pairs federal legislative experience with local roots"],
    ["He won his own primary by two points, so he starts without a unified party behind him",
     "Raised under $86,000 against Moolenaar's $1.65 million and $1.9 million banked",
     "All three raters call MI-2 Solid or Safe R at R+15 [Verify — structural argument]"]),
  thin("Charlotte Magoon", "G"),
  thin("Richard Sills", "NLP",
       extra_diff="Filed by convention on Sept 1, 2026 — after most published voter guides were built",
       extra_opp="Natural Law has no Michigan electoral history to build on [Verify — structural argument]")])

race(3, "U.S. House — Michigan District 3",
 "West Michigan — Grand Rapids, Muskegon, Grand Haven, Wyoming, Kentwood, East Grand Rapids; parts of Kent, Muskegon and Ottawa",
 "REPUBLICANS RECRUITED A 30-YEAR TV METEOROLOGIST, AND SHE WON THE PRIMARY 78.6%–21.4%. Terri DeBoer is a career broadcaster with three decades of name recognition in exactly the media market that is the district, not a conventional political candidate. Scholten was unopposed. Official Secretary of State results: Scholten 112,189 (100%); DeBoer 54,241 (78.56%), Ryan Cushman 14,804 (21.44%). ⚠ THE RATERS DISAGREE HERE: Cook UPGRADED the seat to Solid D in January 2026, Inside Elections still has it only Likely D (May 8, 2026), and Sabato has it Safe D. Cook PVI D+4 — the district has trended left since 2016 and Harris carried it by eight points.",
 [c("Hillary Scholten (incumbent)", "D",
    ["Lower health-care and prescription costs; defend and expand the ACA; paid family and medical leave",
     "Reproductive freedom — protect the right to choose after Dobbs",
     "Jobs and cost-of-living relief in West Michigan"],
    ["Former Department of Justice immigration attorney and a social worker",
     "Flipped a 50-year Republican stronghold in 2022; first Democratic woman to represent West Michigan",
     "$2,329,122 raised, $1,356,572 on hand (FEC, July 15, 2026)",
     "Endorsed by MEA, Michigan AFL-CIO, Planned Parenthood Action Fund, Sierra Club, AIPAC and J Street"],
    ["Cook's own summary notes the district has trended steadily left since 2016, that Harris carried it by eight points and that Scholten won by 10",
     "Better than a four-to-one cash advantage",
     "Cook upgraded the seat from Likely D to Solid D in January 2026"],
    ["Inside Elections still rates it only Likely D, so it is not fully off the board",
     "DeBoer's 30 years of trusted on-air presence is name recognition no ordinary challenger would have",
     "Republicans held this seat for half a century and are campaigning explicitly to return it to those roots"]),
  c("Terri DeBoer", "R",
    ["Expand health-care choice and competition — Direct Primary Care, HSAs, price transparency",
     "Cut taxes and spending to fight inflation; remove regulation on small business",
     "All-of-the-above energy including expanded nuclear; oppose mandates that raise utility bills"],
    ["More than 30 years as a West Michigan broadcast meteorologist; author; from Byron Center",
     "First-time candidate",
     "$551,696 raised, $361,354 on hand (FEC, July 15, 2026)",
     "Won the Republican primary 79%–21% with the Detroit News endorsement"],
    ["Uniquely high, non-political name recognition across exactly the media market that is the district",
     "A health-care-choice and affordability message pitched at swing voters rather than the base",
     "Raised nearly $552,000 as a first-time candidate"],
    ["Running roughly $1.8 million behind the incumbent in a district Harris carried by eight points",
     "No elected experience of any kind",
     "Every rater has the seat Solid, Likely or Safe Democratic [Verify — structural argument]"]),
  thin("Joe Jock", "G")])

race(4, "U.S. House — Michigan District 4",
 "Southwestern Michigan — Kalamazoo and Holland; all of Allegan and Van Buren, plus parts of Ottawa, Kalamazoo, Calhoun and Berrien",
 "MICHIGAN'S SECOND-MOST COMPETITIVE SEAT, AND ONE OF ONLY TWO RATERS HAVE MOVED. Cook shifted it from Likely R to LEAN R in June 2026; Inside Elections and Sabato also have it Lean or Leans R. Cook PVI R+3. ⚠ Huizenga won by 12 points in 2024 but Trump carried the district by only six, and Ottawa County was one of the few Michigan counties where Harris improved on Biden's margin. ⚠ EVERY PUBLIC POLL OF THIS RACE IS PARTISAN-SPONSORED AND THEY DISAGREE: GBAO for McCann had McCann 48–45 (May 28–Jun 1); Ragnar Research for Conservatives for America had Huizenga 48–42 (Mar 12–14); PPP had Huizenga 44–42 (Nov 2025). Official Secretary of State results: Huizenga 71,455 (85.13%) over former Holland mayor Phil Tanis; McCann 65,587 (65.67%) over Diop Harris.",
 [c("Bill Huizenga (incumbent)", "R",
    ["Fight inflation by reining in federal spending",
     "Expand American energy production to cut utility bills",
     "Remove regulation and expand access to capital for local employers"],
    ["In Congress since 2011; Michigan House 2003–09",
     "Co-owns Huizenga Ready-Mix, the family gravel business in Zeeland",
     "$4,093,991 raised, $2,268,746 on hand — verified directly against the FEC API",
     "Passed on the 2026 Senate race and received Trump's endorsement for backing out"],
    ["Fifteen years of incumbency, a $2.27 million war chest and Trump's endorsement in a seat that still leans R+3",
     "Beat a former Holland mayor 85–15, showing no erosion in his own base",
     "Won re-election by 12 points in 2024"],
    ["Cook downgraded him from Likely R to Lean R in June 2026",
     "Cook's own summary notes he won by 12 while Trump carried the district by only six, and that the Grand Rapids region has shifted left",
     "McCann centres the race on Medicaid cuts he says stripped coverage from 160,000 Michiganders",
     "A PPP poll found him at 28% favorable against 40% unfavorable [Verify — a Democratic pollster]"]),
  c("Sean McCann", "D",
    ["Affordability first — tariffs, groceries, doubling utility bills and housing costs",
     "Protect health care — extend ACA tax credits, lower drug prices, strengthen rural and urban access",
     "Build domestic energy infrastructure to bring costs down"],
    ["State senator for Kalamazoo since 2019, now term-limited out; previously Michigan House and Kalamazoo City Commission",
     "$2,620,011 raised, $1,686,240 on hand — verified against the FEC API, unusually strong for a challenger",
     "On the DCCC's Red to Blue list since Feb 23, 2026",
     "Endorsed by Gov. Whitmer, Sen. Slotkin, Michigan AFL-CIO, MEA, UAW Region 1D and Reproductive Freedom for All"],
    ["A rare challenger within striking distance on money, with the full state party apparatus behind him",
     "His own poll showed him ahead 48–45 in June",
     "He has a legislative record to run on — he cites his vote to expand Medicaid to more than a million Michiganders"],
    ["The one Republican-sponsored poll had him down six, and the two polls not run by his own campaign both showed Huizenga ahead",
     "Huizenga still has about $580,000 more banked and 15 years of incumbency",
     "No rater has moved this seat past Lean R — nobody calls it a toss-up"]),
  thin("Shafina Che Barnett", "G",
       extra_opp="In a two-way race consuming essentially all the district's resources, a third line struggles for attention [Verify — structural argument]")])

race(5, "U.S. House — Michigan District 5",
 "The entire southern tier — Michigan's whole border with Indiana and Ohio. All of Branch, Cass, Hillsdale, Jackson, Lenawee and St. Joseph, most of Monroe and Calhoun",
 "BOTH NOMINEES WERE UNOPPOSED, so no primary money was spent and no upset was possible: Walberg 77,105 (100%) and Vukasovich 64,425 (100%) on the Secretary of State's official results. Cook PVI R+13; Solid or Safe R at all three raters, none of which has engaged with the race this cycle. Five candidates are on the November ballot, the second-longest in the state. ⚠ NOT ASSERTED: the U.S. Taxpayers nominee here shares a name with a Democrat who ran against Walberg in the 2000s. We did not confirm they are the same person and do not claim it.",
 [c("Tim Walberg (incumbent)", "R",
    ["National security — strengthening resolve and capabilities against terrorist threats and hostile regimes",
     "Jobs and fiscal responsibility — the federal government should live within its means",
     "Affordable health care — lower prescription costs, combat addiction, protect pre-existing conditions"],
    ["Former pastor; Michigan House 1983–1999; in Congress 2007–09 and again since 2011",
     "$1,742,398 raised, $993,833 on hand (FEC, July 15, 2026)",
     "Endorsed by Trump and AIPAC",
     "Faced no primary opposition at all"],
    ["Cook's summary is blunt — the district is solidly conservative, insulating him from any serious electoral challenge",
     "Nearly $1 million banked against a challenger with about $13,000",
     "No primary opponent in a district he has represented for most of two decades"],
    ["Vukasovich's wages-and-labour message targets a district with real manufacturing decline",
     "At R+13 with no rater engagement he has faced little scrutiny and no debate pressure this cycle [Verify — structural argument]",
     "Long tenure invites the standard generational-change argument [Verify — structural argument]"]),
  c("Christian Vukasovich", "D",
    ["Raise wages, protect union jobs, invest in local manufacturing and infrastructure",
     "Lower prescription costs, protect pre-existing-condition coverage, expand rural access; supports Medicare for All",
     "Education funding and getting money out of politics"],
    ["Lifelong teacher and college professor",
     "Union organiser with the AAUP and an NEA member",
     "$55,756 raised, $13,290 on hand (FEC, through June 30, 2026)",
     "Endorsed by Lenawee Indivisible"],
    ["An authentic labour organiser's profile in a working-class district",
     "Ran unopposed, so he enters the general with a unified party",
     "His affordability and rural-health message maps onto the district's actual economics"],
    ["Outraised roughly 31 to one, with under $14,000 on hand",
     "No rater lists MI-5 as anything but Solid or Safe R at R+13",
     "No independent or party polling of this race could be located [Verify — an absence of located records]"]),
  thin("Ronald A. Muszynski", "L"),
  thin("Sharon Marie Renier", "UST",
       extra_opp="A name-match with a 2000s Democratic candidate against Walberg was NOT confirmed and is not asserted here [Verify]"),
  thin("Jim Bronke", "G")])

write("h1to5.js")
