const HOUSE_RACES = {
  1: { name: "U.S. House — Michigan District 1", region: "All 15 Upper Peninsula counties plus 20 in the northern Lower Peninsula — Traverse City, Marquette, Alpena, Sault Ste. Marie",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "BERGMAN TOOK 74.3% OF A THREE-WAY PRIMARY — BUT FOUR OF HIS OWN REGION'S REPUBLICAN LEGISLATORS HAD PULLED THEIR ENDORSEMENTS IN FEBRUARY. State Reps. Bohnak, Markkanen, McBroom and Prestin rescinded over a state Senate dispute; he won anyway. ⚠ Challenger Matthew DenOtter SELF-FUNDED $1,877,175 of his $1,906,389 — nearly matching Bergman's entire raise — and got 13.1%. Callie Barr won the Democratic primary with 58.5% and is running a rematch of 2024. Cook PVI R+11; Solid/Safe R at all three raters. Official SoS results: Bergman 80,726 (74.33%), DenOtter 14,254, Justin Michal 13,627; Barr 62,197 (58.49%), Kyle Blomquist 37,936, Wayne Stiles 6,213.",
        candidates: [
          { name: "Jack Bergman (incumbent)", party: "R", winner: false,
            positions: ["Secure the border and enforce immigration law","Strengthen national defense and veterans' services","Rein in federal spending"],
            differentiators: ["Retired U.S. Marine Corps lieutenant general; in Congress since 2017","Rural broadband is his signature local bill (H.R.4905, H.R.1610)","$1,917,574 raised, $660,163 on hand (FEC, July 15, 2026)","Endorsed by Trump (Nov 1, 2025) and AIPAC"],
            supporters: ["Delivers concrete federal money to a vast rural district — broadband, the Soo Locks, VA services","Rank and seniority give the Upper Peninsula reach it would not otherwise have","Holds Trump's endorsement in an R+11 seat"],
            opponents: ["Four Upper Peninsula Republican legislators publicly rescinded their endorsements in February 2026","At 78 he is the oldest member of Michigan's delegation — Cook's own race summary says so","Barr's campaign frames him as absent, running on 'the places Jack Bergman forgets'"] },
          { name: "Callie Barr", party: "D", winner: false,
            positions: ["Federal funding for local homebuilding, zoning reform, limits on short-term rentals","PRO Act, protect Social Security and remove the payroll cap","Protect Medicaid and rural hospitals; extend ACA subsidies plus a public option"],
            differentiators: ["Attorney and former high-school teacher from Traverse City","The 2024 nominee for this seat — this is a rematch","Became her Marine husband's caretaker, then a veterans' advocate","$824,340 raised, $530,724 on hand (FEC, July 15, 2026)","Endorsed by Pete Buttigieg, former Rep. Bart Stupak, EMILYs List and VoteVets"],
            supporters: ["Consolidated the primary at 58% and has the strongest cash position of any recent MI-1 Democrat","Her affordability and rural-hospital message is aimed at the district's actual economics","National women's and veterans' groups moved in immediately after the primary"],
            opponents: ["She lost this district in 2024 and faces the same R+11 arithmetic","Trails Bergman better than two to one in money raised","All three raters call the seat Solid or Safe R, so outside money is unlikely to arrive [Verify — structural argument]"] },
          { name: "Arnett Satterla", party: "L", winner: false,
            positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
            differentiators: ["Nominated at the Libertarian Party state convention","On the Secretary of State's certified November list","No FEC fundraising located [Verify — an absence of located records]"],
            supporters: ["Gives libertarian voters in a Solid R seat a ballot line of their own [Verify — structural argument]"],
            opponents: ["No campaign fundraising or platform could be located [Verify — an absence of located records]","Minor parties have no history of meaningful vote share in this district [Verify — structural argument]"] },
          { name: "Doc Kovaly", party: "I", winner: false,
            positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
            differentiators: ["U.S. Taxpayers Party nominee, chosen at convention","On the Secretary of State's certified November list","No FEC fundraising located [Verify — an absence of located records]"],
            supporters: ["Offers a socially conservative alternative to the Republican nominee [Verify — structural argument]"],
            opponents: ["No campaign fundraising or platform could be located [Verify — an absence of located records]","The U.S. Taxpayers line draws low single digits in Michigan [Verify — structural argument]"] },
          { name: "LaVeta Davenport", party: "G", winner: false,
            positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
            differentiators: ["Green Party nominee, chosen at convention","On the Secretary of State's certified November list","No FEC fundraising located [Verify — an absence of located records]"],
            supporters: ["Gives left-of-Democratic voters a ballot option in a seat Democrats are unlikely to win [Verify — structural argument]"],
            opponents: ["No campaign fundraising or platform could be located [Verify — an absence of located records]","Green candidates have drawn about one percent in this district [Verify — structural argument]"] },
          { name: "Liz Hakola", party: "I", winner: false,
            positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
            differentiators: ["Working Class Party nominee; also its MI-1 nominee in 2022 and 2024","On the Secretary of State's certified November list","No FEC fundraising located [Verify — an absence of located records]"],
            supporters: ["A third run gives her the most name recognition of the minor-party field here [Verify — structural argument]"],
            opponents: ["Did not win in 2022 or 2024 and has no located campaign operation [Verify — an absence of located records]","No fundraising located [Verify — an absence of located records]"] },
          { name: "Zebulon Featherly", party: "I", winner: false,
            positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
            differentiators: ["Qualified with No Party Affiliation — the only true independent on the MI-1 ballot","On the Secretary of State's certified November list","No FEC fundraising located [Verify — an absence of located records]"],
            supporters: ["The only candidate here with no party label at all, in a district where both parties are unpopular [Verify — structural argument]"],
            opponents: ["No campaign fundraising or platform could be located [Verify — an absence of located records]","Independents without ballot-line infrastructure rarely clear low single digits in Michigan [Verify — structural argument]"] }
        ] }
    ] },
