// Michigan STATEWIDE 2026 ballot.
//
// SOURCES: the Michigan Bureau of Elections' own "Unofficial Candidate Listing — All State and
// Judicial Offices, General Election, Tuesday, November 3, 2026" (721 candidates, generated
// Sept 3, 2026 07:49 EDT) at mi-boe.entellitrak.com; the Secretary of State's machine-readable
// county canvass of the Aug 4 primary (mvic.sos.state.mi.us, all 83 counties); the Board of State
// Canvassers' own meeting agendas and its Statewide Petition Status document; the Bureau's
// "Filing for Office" guides; Const 1963 art V §§ 21 and 30 and MCL 168.52, .73, .282, .591 via
// legislature.mi.gov; Cook Political Report, Sabato's Crystal Ball, Inside Elections; FEC and
// Transparency USA; Michigan Advance, Bridge Michigan, Votebeat, Michigan Public, Detroit News.
//
// ⚠⚠ NOTHING ON THE BALLOT-PROPOSAL SIDE IS FINAL UNTIL SEPT 4, 2026. The Secretary of State must
// certify ballot contents to county clerks by 5 p.m. that day, and the Board of State Canvassers
// meets that morning to finalise. Everything below is stated AS OF SEPT 3, 2026 and the proposal
// NUMBERING in particular is provisional.
// ⚠ WE DO NOT SAY THE AUG 4 PRIMARY IS "CERTIFIED". The Board's Aug 24 agenda carried the canvass
// as item 2, the county canvass is complete for all 83 counties, and the Bureau's own Nov 3
// candidate listing — which is downstream of that canvass — names the nominees. But no Aug 17 or
// Aug 24 minutes are posted and no news report confirms the vote, so the page says "official
// county-canvassed results". ⚠ The AP/Yahoo story "Michigan's elections panel certifies results of
// August primary election" is dated AUG 19, 2022 and was NOT used.
//
// ⚠ THREE PREMISES IN OUR OWN BUILD BRIEF WERE WRONG AND ARE CORRECTED HERE:
//   (1) Detroit Mayor Mike Duggan is NOT running as an independent. He WITHDREW on May 21, 2026,
//       about eight weeks before the July 16 independent filing deadline, and never submitted
//       petitions. There is no independent ticket for governor.
//   (2) The Senate primary margin is 13,792 votes / 0.897%, not the 14,926 / 0.975% we had.
//   (3) The Noah Hood nomination we held back as "counterintuitive and single-sourced" is real and
//       not counterintuitive at all: GOV. WHITMER APPOINTED HIM in April 2025, which is exactly why
//       Democrats nominated him. It is published here.
const STATEWIDE = [
  { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · Statewide", office: "U.S. Senate — Michigan (OPEN SEAT)",
    note: "OPEN SEAT AND A TOSS-UP AT ALL THREE RATERS — one of only four Senate races Sabato calls a toss-up. Gary Peters (D) announced on Jan 28, 2025 that he would not seek re-election. ⚠ THE DEMOCRATIC PRIMARY WAS DECIDED BY 13,792 VOTES: Abdul El-Sayed 744,952 (48.45%) to Haley Stevens 731,160 (47.55%), with Mallory McMorrow at 61,516 (4.00%) — a margin of 0.897%, about nine times Michigan's 0.1% automatic-recount threshold. Mike Rogers was unopposed with 883,328. Figures are the Secretary of State's own county canvass, all 83 counties. ⚠ Stevens gave up MI-11 to run, which is why that seat is open. ✅ Cook Toss Up (Aug 20), Sabato Toss-up (Aug 26), Inside Elections Toss-up. ⚠ One public poll: EPIC-MRA on Aug 31 had El-Sayed 47, Rogers 43.",
    candidates: [
      { name: "Abdul El-Sayed", party: "D", winner: false,
        positions: ["Money out of politics — ban corporate money, end gerrymandering, abolish the filibuster","Money in your pocket — tax billionaire wealth, housing costs, data centres","Medicare for All"],
        differentiators: ["Former executive director of the Detroit Health Department and Wayne County health director","Lost the 2018 gubernatorial primary to Gretchen Whitmer","Top fundraiser in the race at $14.5 million (FEC, through July 15, 2026) against Rogers's $10.9 million","A coalition spanning Sanders, Warren, Ocasio-Cortez and Tlaib as well as Kamala Harris"],
        supporters: ["He led 47–43 in an EPIC-MRA poll released Aug 31, 2026","He out-organised two better-known Democrats and beat the party establishment's preferred candidate","He has the largest war chest in the race"],
        opponents: ["Rogers was recorded telling donors in June that El-Sayed as the nominee put Republicans in good shape","Party division outlasted the primary: at the Aug 29 convention he apologised for comments on the West Bloomfield synagogue attack that some read as justifying it, and met the state party's Jewish Caucus","Rogers's campaign runs an attack claiming Medicare for All would close 35 rural hospitals [Verify — a campaign allegation, not independently verified]"] },
      { name: "Mike Rogers", party: "R", winner: false,
        positions: ["A housing and cost-of-living plan — 529 accounts for down payments, rent-based credit building","Manufacturing and lower prices; protect Social Security and Medicare","Alignment with President Trump"],
        differentiators: ["U.S. Representative 2001–2015 and chair of the House Intelligence Committee; former FBI agent","The 2024 Senate nominee — lost to Elissa Slotkin by about three tenths of a point","$10.9 million raised (FEC, through July 15, 2026), with a lower burn rate than his opponent","Endorsed by Trump; launched a Democrats for Mike Rogers coalition with state Rep. Karen Whitsett"],
        supporters: ["He came within 0.3 points in 2024, a worse year for Republicans in Michigan","The deepest national-security résumé in the race","He enters the general with more cash preserved relative to what he raised"],
        opponents: ["He trailed 43–47 in the Aug 31 EPIC-MRA poll","The 'Florida man' residency attack has followed him since 2024 — though Bridge Michigan's own fact-check finds he is a Livingston County native who does live in White Lake","Losing a Senate race in 2024 and running again invites the argument that the party had no better option [Verify — structural argument]"] },
      { name: "Lydia Christensen", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at party convention","From Ironwood in the Upper Peninsula; a member of the Kiowa-Sioux Nation; nominated at Troy on June 28, 2026","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["She runs on civil-liberties absolutism plus an opt-in Medicaid for All, expanded Social Security and a $15 minimum wage indexed to inflation — an unusual combination for a Libertarian [Verify — positions via LP.org and Independent Political Report]","Gives libertarian voters a ballot line of their own [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["Her nomination drew public criticism from a Libertarian National Committee regional representative as off-platform","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Tim Long", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Offers an alternative to both major-party nominees [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["His own party publishes NO content for him while 13 other U.S. Taxpayers nominees have full biographies on the same site [Verify — read from the party's own candidate API]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Douglas P. Marsh", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at party convention","The Green Party's 2026 Senate nominee, as he was in 2024","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives voters to the left of the Democratic nominee a ballot line [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No candidate-specific platform could be located — the Michigan Green Party's candidate pages are login-gated [Verify]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Walter P. Kristy", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Natural Law nominee, chosen at party convention","Filed on Aug 31, 2026, more than four months after the major parties","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Offers an alternative to both major-party nominees [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["He filed too late to appear in Michigan Advance's voter guide, and the only biographical line located is a single-sourced directory entry [Verify]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide", office: "Governor and Lieutenant Governor of Michigan (OPEN SEAT)",
    note: "OPEN SEAT — GRETCHEN WHITMER IS TERM-LIMITED under Const 1963 art V § 30, which bars anyone from being elected more than twice to governor, lieutenant governor, secretary of state or attorney general. ⚠⚠ MIKE DUGGAN IS NOT ON THIS BALLOT. The former Detroit mayor's independent bid ended when he WITHDREW on May 21, 2026, about eight weeks before the July 16 independent deadline; he never filed petitions. He cited a national Democratic surge, a state Senate special election Democrats won easily, a Chamber poll showing him 11 points behind, and an inability to raise money outside Michigan — 94% of his donors were in-state. ⚠ HOW THE TICKET WORKS: only the GOVERNOR is nominated at the August primary. Const 1963 art V § 21 has the lieutenant governor nominated at a party CONVENTION, and in November one vote is cast jointly for both. James named DeBoyer on Aug 14; Democratic delegates formally nominated Brinks on Aug 29. Primary results, official county canvass: Benson 1,251,160 (83.22%) over Christopher Swanson; James 466,714 (50.05%) over Perry Johnson 328,194, Mike Cox 121,261 and Aric Nesbitt 16,295. ✅ Cook Lean Democrat (Aug 27), Sabato Leans Democratic (moved off Toss-up July 23), Inside Elections Tilt Democratic.",
    candidates: [
      { name: "Jocelyn Benson & Winnie Brinks", party: "D", winner: false,
        positions: ["Affordability — housing, health care and childcare costs","Lower electricity and energy costs, including a position on data centres","Education — moving Michigan's public schools into the national top ten"],
        differentiators: ["Benson is the sitting Secretary of State, term-limited, and a former dean of Wayne State Law","Brinks is Senate Majority Leader, the first woman to hold the post, and has served since 2012","Top fundraiser at $5.96 million (Transparency USA, through July 20, 2026)","The first all-woman governor and lieutenant governor ticket in Michigan history"],
        supporters: ["Two prior statewide wins for Benson, and a concrete legislative record for Brinks from the 2023 trifecta — the red-flag law, LGBTQ anti-discrimination protections, a clean-energy standard, Right-to-Work repeal and the retirement-tax repeal","She leads in money and in all three ratings","A joint ticket pairing statewide administrative experience with legislative leadership"],
        opponents: ["Republicans tie Benson to the Southern Poverty Law Center, where she was a board member 2014–18 and which is now under federal indictment — but Bridge Michigan's fact-check is explicit that she is not named in that indictment","Bridge's donor analysis found she raised more money from about 4,400 donors while James raised from about 8,000, and that he raised more of it in-state","An open seat with no incumbent is structurally more volatile than a defended one [Verify — structural argument]"] },
      { name: "John James & Jason DeBoyer", party: "R", winner: false,
        positions: ["Freedom from corruption — ethics and transparency, with a pledged personal financial disclosure","Growth and opportunity for small business and skilled careers","Education and families — parental rights and fair play in girls' sports"],
        differentiators: ["James is the sitting U.S. Representative for MI-10, a West Point graduate and Iraq veteran","He was the Republican Senate nominee in 2018 and 2020, losing to Debbie Stabenow 45.76%–52.26%","DeBoyer is a state representative, chairs House Oversight, and is a former St. Clair County clerk who ran elections","Endorsed by Trump, with an aligned super PAC, Mission Michigan"],
        supporters: ["The only genuine outsider ticket in the race, running an explicit clean-up-Lansing case","A broader donor base of about 8,000, including the Van Andel, Secchia and Haworth families","A Republican strategist has argued that as a former clerk DeBoyer can speak credibly about elections"],
        opponents: ["It is the first Republican statewide ticket since 1978 with no woman on it","DeBoyer's district nearly abuts James's, which concentrates the ticket geographically","Democrats push a 'John James tax' attack on small businesses [Verify — a campaign claim, not independently verified]","James vacated MI-10 to run, leaving a toss-up open seat his party must now defend"] },
      { name: "Anthony Hudson & Beau Parmenter", party: "L", winner: false,
        positions: ["Eliminate property and state income taxes","A part-time legislature, end annual vehicle registration, move auto insurance from no-fault to at-fault","Ban solar and wind on state land; end renewable and electric-vehicle mandates"],
        differentiators: ["Hudson is a 20-year truck driver and a former Republican who left the party in February 2026","The only minor-party ticket with meaningful money — $13,682 raised","Libertarian nominee, chosen at the party's convention"],
        supporters: ["A specific, itemised tax and regulatory platform rather than a protest candidacy","A working truck driver rather than a career politician","Libertarians took 1.33% in Michigan's 2018 governor's race, the strongest minor-party showing [Verify — computed from the state's own 2018 results file]"],
        opponents: ["The Oakland County Republican Party said his switch followed months of struggling to demonstrate any viable path","Michigan Advance reported his repeated use of threats, including hanging officials for treason","All minor-party tickets combined took about 2.9% in the 2018 governor's race [Verify — structural argument]"] },
      { name: "Donna Brandenburg & Robert Cowper II", party: "I", winner: false,
        positions: ["Eliminate property and income taxes","Create a state department of government efficiency","Ironclad election integrity — paper ballots, voter ID and same-day counting"],
        differentiators: ["Brandenburg is the U.S. Taxpayers Party state chair","⚠ In 2022 she was one of five Republican gubernatorial candidates removed from the primary ballot after the Bureau of Elections found an unprecedented number of fraudulent petition signatures — 19 circulators and 11,144 signatures were set aside from about 27,500 filed","The Michigan Supreme Court declined to overturn that removal","$0 raised"],
        supporters: ["A published, itemised platform, which is more than most minor-party tickets offer","Leading her own party's ticket gives the U.S. Taxpayers line a recognised name"],
        opponents: ["The 2022 ballot removal for fraudulent petition signatures is a matter of public record, including her own mandamus complaint on the Michigan Supreme Court's website","$0 raised against tickets with millions","The U.S. Taxpayers ticket took 0.69% in the 2018 governor's race [Verify — computed from the state's own 2018 results file]"] },
      { name: "Douglas Campbell & Bobbie Clay", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at party convention","Filed Aug 3, 2026; confirmed on the Michigan Green Party's own site","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives voters to the left of the Democratic nominee a ballot line [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["$0 raised and $0 spent; the Green ticket took 0.68% in the 2018 governor's race [Verify — computed from the state's own 2018 results file]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide", office: "Attorney General of Michigan (OPEN SEAT)",
    note: "OPEN SEAT, AND IT WAS NEVER ON A PRIMARY BALLOT. Dana Nessel is term-limited under Const 1963 art V § 30. ⚠ MICHIGAN NOMINATES ITS ATTORNEY GENERAL AND SECRETARY OF STATE AT PARTY CONVENTIONS, NOT AT THE AUGUST PRIMARY — Const 1963 art V § 21, confirmed by the Bureau of Elections' own filing guide (signatures 'N/A'; file with the Bureau one business day after the convention) and by the Aug 4 results file, which contains NO attorney general, secretary of state, Supreme Court or education-board contest anywhere in it. ⚠ EACH PARTY RAN A TWO-STEP PROCESS: an ENDORSEMENT convention and then a statutory NOMINATING convention. Republicans endorsed Doug Lloyd at Novi on Mar 28, 2026 in a contested delegate ballot; Democrats formally nominated Eli Savit at the Lansing Center on Aug 29, 2026. ⚠ The Republican nominating convention date is [Verify] — every Republican certificate was filed Monday Aug 24, and MCL 168.73 requires filing within one business day, which points to Sat Aug 22, but it could not be sourced directly. Bipartisan bills would move these nominations to the August primary starting in 2027.",
    candidates: [
      { name: "Eli Savit", party: "D", winner: false,
        positions: ["Defend workers — fight wage theft, payroll fraud and labour trafficking","Protect consumers — litigate price gouging and deceptive practices; revive Michigan's Consumer Protection Act","Civil-rights enforcement as the federal government retreats, and environmental litigation including PFAS"],
        differentiators: ["Washtenaw County Prosecutor; former senior legal counsel to the City of Detroit","Clerked for Justice Ruth Bader Ginsburg; began his career as a public school teacher","Built the state's only stand-alone prosecutor's unit for worker and consumer rights","Nominated Aug 29 with an explicit pledge to sue the Trump administration"],
        supporters: ["The deepest civil-rights and environmental-litigation résumé in the race — he would be the first Michigan attorney general to have practised as an environmental lawyer for states","He created a first-in-the-state prosecutorial unit rather than inheriting one","Supporters argue Democratic attorneys general have recovered federal funding that would otherwise have been cut"],
        opponents: ["Lloyd's platform is a direct rebuttal — a pledge to prosecute without political favour and to stand against what he calls political lawfare and weaponised prosecutions","Critics of an activist attorney general's office argue multistate litigation crowds out ordinary state law enforcement [Verify — structural argument; no specific news-reported attack on Savit was located this pass]"] },
      { name: "Doug Lloyd", party: "R", winner: false,
        positions: ["Prosecute criminals fairly, without political favour or bias","Stand against political lawfare and weaponised prosecutions","Root out corruption, stop political overreach and defend Michigan's sovereignty"],
        differentiators: ["Eaton County Prosecutor for more than 30 years","Past president of the Prosecuting Attorneys Association of Michigan — elected by his peers","Led enforcement on fraud and economic crimes","Won a contested delegate ballot at the March endorsement convention"],
        supporters: ["He runs on prosecutorial experience rather than political profile","His site lists endorsement blocks from sheriffs, prosecutors, state legislators and law-enforcement organisations [Verify — the names are JavaScript-loaded and could not be extracted]","Peer election to lead the state prosecutors' association is a credential no other candidate has"],
        opponents: ["Democrats read the no-lawfare plank as a pledge to stand down from the multistate litigation Nessel used against the Trump administration — which both Savit and Gilchrist made the centrepiece of their convention speeches [Verify — structural argument]","A county prosecutor's office is far smaller than the department he would run [Verify — structural argument]"] },
      { name: "Jason Dye", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives libertarian voters a ballot line of their own [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "John Perry Ludtke Jr.", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Offers an alternative to both major-party nominees [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["His own party publishes no content for him [Verify — read from the party's own candidate API]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Jeff Polonowski", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives voters to the left of the Democratic nominee a ballot line [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No candidate-specific platform could be located — the Michigan Green Party's candidate pages are login-gated [Verify]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Doug Dern", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Natural Law nominee, chosen at party convention","The Natural Law Party's 2018 Supreme Court candidate, when he took 209,103 votes","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Offers an alternative to both major-party nominees [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["Filed Aug 31, 2026, too late to appear in Michigan Advance's voter guide","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide", office: "Secretary of State of Michigan (OPEN SEAT)",
    note: "OPEN SEAT — Jocelyn Benson is term-limited under Const 1963 art V § 30, and is her party's nominee for governor. ⚠ LIKE THE ATTORNEY GENERAL, THIS OFFICE IS NOMINATED AT PARTY CONVENTIONS, NOT AT THE AUGUST PRIMARY (Const 1963 art V § 21). Republicans endorsed Anthony Forlini at Novi on Mar 28, 2026; Democrats nominated Lieutenant Governor Garlin Gilchrist II at the Lansing Center on Aug 29, 2026. THE TWO CANDIDATES ARE CAMPAIGNING ON OPPOSITE SIDES OF THE SAME QUESTION — what happens to Michigan voters' data. Gilchrist runs on refusing to hand voter registration and licence-plate data to the federal government or to big technology companies; Forlini runs on using all public databases to remove ineligible voters and on watermarked ballots. Both also promise shorter branch-office wait times.",
    candidates: [
      { name: "Garlin Gilchrist II", party: "D", winner: false,
        positions: ["Protect voter data — stand against federal and big-technology demands for voter registration and licence-plate data","Modernise licensing and registration with 21st-century service","More legislative action on dark money in politics"],
        differentiators: ["Sitting Lieutenant Governor since 2019 and Michigan's first Black lieutenant governor","A former software engineer, who frames the office as a service-delivery problem","Eight years as a statewide officeholder","Endorsed by the Michigan Education Association, United Steelworkers District 1, the Northern Midwest Regional Council of Carpenters and the Michigan Working Families Party"],
        supporters: ["At the Aug 29 convention he made the federal Justice Department's request for Michigan's voter rolls the core of his case — that a voter's data should belong to the voter","An engineer running the state's largest customer-service operation is an unusual and specific fit","Eight years of statewide name recognition"],
        opponents: ["Forlini's whole platform is an operational critique of the administration Gilchrist has served in — long waits, unanswered phones and insufficient list maintenance","He has never run an election office, while his opponent has run one of Michigan's largest [Verify — structural argument]"] },
      { name: "Anthony G. Forlini", party: "R", winner: false,
        positions: ["Election integrity — watermarked ballots statewide, use all public databases to remove ineligible voters","Stop sending voter information to third-party groups","Service delivery — cut Secretary of State wait times, improve election-worker training, audit county clerks for consistency"],
        differentiators: ["Macomb County Clerk since 2020 — the only candidate who has actually run elections","Three terms in the Michigan House, 2011–2017; former township supervisor and businessman","Campaigns on measurable clerk-office results: a forensic audit, watermarked ballots, referring double voters for prosecution, removing deceased voters, wait times under four minutes","Son of an Italian immigrant"],
        supporters: ["Operational credibility — he runs on clerk-office metrics rather than national politics, and pledges to keep politics out of the office","The only candidate in the race with hands-on election administration experience","A county-level record voters can check"],
        opponents: ["Democrats read the watermarked-ballot and database agenda as importing 2020 election-fraud premises into statewide administration","The same voter-data question drives his opponent's campaign from the opposite direction, so the contrast is sharp and unavoidable [Verify — structural argument; no direct news-reported criticism of Forlini was located this pass]"] },
      { name: "Christine Sloan", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives libertarian voters a ballot line of their own [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] },
      { name: "Scott E. Aughney", party: "I", winner: false,
        positions: ["Election integrity, from the perspective of an election-records requester","No further published 2026 platform could be located [Verify — an absence of located records]",""],
        differentiators: ["U.S. Taxpayers Party nominee, from Jackson County","Self-described election-integrity investigator and whistleblower; a founding member of Citizens for Electoral Justice","Filed a pro se Court of Claims suit against then-Secretary of State Benson in May 2024 alleging obstruction of a records request over election data [Verify — from his party's own biography]","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["He has actually litigated for access to Michigan election records, which is an unusually direct qualification for the office [Verify — via his party's own biography]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["A suit against the incumbent he seeks to replace invites the argument that the candidacy is a grievance rather than a programme [Verify — structural argument]","No campaign fundraising or independent coverage could be located [Verify — an absence of located records]"] },
      { name: "Eric Borregard", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Gives voters to the left of the Democratic nominee a ballot line [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "Judicial · Statewide", office: "Michigan Supreme Court — two seats (NONPARTISAN ballot section)",
    note: "TWO EIGHT-YEAR SEATS, AND THE BALLOT LINE IS NONPARTISAN EVEN THOUGH THE NOMINATIONS ARE NOT. Candidates reach the ballot by nomination at a party convention, then appear in the nonpartisan section — the Bureau of Elections' own filing guide says so, and incumbents may alternatively file an affidavit, though both took the convention route this year. The seats up are the two won in 2018 by Elizabeth Clement and Megan Cavanagh, expiring Jan 1, 2027. ⚠ WHY JUSTICE HOOD IS AN INCUMBENT ON A DEMOCRATIC NOMINATION: GOV. WHITMER APPOINTED HIM on Apr 23, 2025 to the seat of Chief Justice Elizabeth Clement, who retired Apr 15, 2025 — which is precisely why Clement's 2018 seat is one of the two up this year. This page held that fact back on a previous pass as counterintuitive and single-sourced; it is now confirmed three independent ways, including the Bureau's own filing record (Hood and Cavanagh both filed Aug 31, 2026 by convention, the date of every Democratic convention filing, while Republicans filed Aug 24). Justices nominated by Democrats or appointed by Whitmer hold a 6–1 majority. ✅ NO RATER COVERS THIS RACE — Cook, Sabato and Inside Elections publish ratings only for President, U.S. House, U.S. Senate and Governor, checked at each site.",
    candidates: [
      { name: "Megan Kathleen Cavanagh (incumbent)", party: "I", winner: false,
        positions: ["Child-welfare outcomes and family legal representation","Collaboration with tribal courts","Access to justice for litigants without lawyers [Verify — drawn from her campaign site's framing]"],
        differentiators: ["Chief Justice; elected to the court in 2018","Daughter of a longtime Michigan Supreme Court justice","University of Michigan environmental engineering, then Wayne State Law while working full-time","More than 15 years in Detroit appellate practice","Nominated by the Democratic Party, Aug 31, 2026"],
        supporters: ["An eight-year record on the court and a specific administrative focus on children and families","Appellate practice experience directly relevant to the work of the court","Re-nominated by her party without a contest"],
        opponents: ["Republican nominees argue the court's Democratic-nominated majority decides cases on policy rather than text — the explicit case both Warren and Morse-Bills make","Her father's service on the same court invites a dynasty critique [Verify — structural argument]"] },
      { name: "Noah P. Hood (incumbent)", party: "I", winner: false,
        positions: ["Criminal law and fraud enforcement experience applied to appellate review [Verify — drawn from his biography and campaign site]","Veterans' courts and problem-solving courts","No further itemised judicial philosophy is published [Verify — an absence of located records]"],
        differentiators: ["Appointed to the Supreme Court by Gov. Whitmer in April 2025, filling Chief Justice Clement's seat","Born 1986 on Detroit's east side; Cass Tech valedictorian, then Yale and Harvard Law","Assistant U.S. Attorney in Toledo — fraud, money laundering and crimes against children","Wayne County Circuit Court 2019, including its Veterans Treatment Court; Court of Appeals 2022","Nominated by the Democratic Party, Aug 31, 2026"],
        supporters: ["A prosecutor's and trial judge's experience alongside appellate service","He founded and ran a veterans' treatment docket, which is concrete problem-solving work","The fastest-rising judicial career in the state — circuit court to the Supreme Court in six years"],
        opponents: ["He has never faced Michigan voters — this is his first election to the seat he was appointed to","Republicans argue the Whitmer appointments produced a 6–1 court that no longer reflects the state [Verify — structural argument]"] },
      { name: "Michael Warren", party: "I", winner: false,
        positions: ["Interpret the law as written; do not legislate from the bench","Civic education as a judicial responsibility","Trial experience should inform appellate decision-making"],
        differentiators: ["Oakland County Circuit judge for more than 20 years","More than 400 jury trials — his campaign claims more trial experience than the entire current Supreme Court combined","University of Michigan Law, cum laude; business law professor at Wayne State; taught constitutional law at Cooley","Author of America's Survival Guide and co-founder of Patriot Week","Nominated by the Republican Party, Aug 24, 2026"],
        supporters: ["Far more trial experience than any sitting justice, on his own account","Two decades on the bench in Michigan's second-largest county","A published record on constitutional and civic education"],
        opponents: ["Michigan has not elected a Republican-nominated justice to an open seat against two incumbents in recent memory, and he faces two at once [Verify — structural argument]","Critics of the textualist framing argue it is itself a policy position [Verify — structural argument]"] },
      { name: "Casandra Morse-Bills", party: "I", winner: false,
        positions: ["Apply the law as written rather than reshape it","Rural and northern Michigan access to the courts [Verify — inferred from her circuit's geography and her campaign framing]","No further itemised judicial philosophy is published [Verify — an absence of located records]"],
        differentiators: ["Presiding Judge of the 23rd Judicial Circuit — Alcona, Arenac, Iosco and Oscoda counties, one of Michigan's largest by area","Hears probate, district and circuit cases, an unusually broad docket","Elected 2018, re-elected 2024; member of the Michigan Judicial Council","Nominated by the Republican Party, Aug 24, 2026"],
        supporters: ["A working trial judge from northern Michigan on a court dominated by appointees from the southeast","A broad docket across three court levels is unusual breadth","Twice elected by her own voters"],
        opponents: ["She faces two incumbents in a state where sitting justices are rarely defeated [Verify — structural argument]","A small rural circuit is far removed from the caseload of the state's highest court [Verify — structural argument]"] },
      { name: "Jody White", party: "I", winner: false,
        positions: ["End judicial self-discipline without public accountability","Probate-court reform","Expanded use of civil mediation [Verify — from her party's own biography]"],
        differentiators: ["U.S. Taxpayers Party nominee, confirmed on the party's own candidate list","Licensed Michigan real estate broker for more than 40 years","About a decade of probate-court reform advocacy across six counties; co-founder of a statewide judicial accountability initiative","Trained civil mediator; has published position papers"],
        supporters: ["She is the only candidate running specifically on judicial accountability and probate-court reform","She has published actual position papers, which most minor-party judicial candidates do not"],
        opponents: ["No legal training or judicial experience is claimed [Verify — an absence of located records]","Minor-party judicial candidates in Michigan have not won a Supreme Court seat [Verify — structural argument]"] },
      { name: "Thomas W. Howe", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at party convention","On the Secretary of State's certified November candidate list","No FEC fundraising located [Verify — an absence of located records]"],
        supporters: ["Offers an alternative to both major-party nominees [Verify — structural argument]","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No platform material exists even on the party website that nominated him [Verify — read from the party's own candidate API]","No campaign platform, website or fundraising could be located [Verify — an absence of located records]","Minor-party candidates in Michigan U.S. House races draw low single digits [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "Judicial · Statewide", office: "Michigan Court of Appeals — eight seats, ALL UNOPPOSED",
    note: "EVERY COURT OF APPEALS SEAT ON THIS BALLOT HAS EXACTLY ONE CANDIDATE — the sitting judge, who reached the ballot by affidavit of candidacy rather than by convention. That is the whole story of these races, and it is worth a voter knowing: eight appellate judgeships are being filled without a contest. The seats are 1st District (three full terms: Mariam Saad Bazzi, Anica Letica, Christopher M. Murray; plus one partial term to Jan 1, 2031: Andrew J. Lievense), 2nd District (Sima G. Patel, Christopher M. Trebilcock), 3rd District (Mark T. Boonstra, Daniel S. Korobkin) and 4th District (Michael J. Kelly, Allie Greenleaf Maldonado, Michelle M. Rick). ⚠ These appear in the NONPARTISAN section of the ballot. Individual candidate cards are deliberately not carded here: with no opponent there is no contest to inform, and no campaign material exists for an unopposed appellate incumbent. The names are listed above so a voter can look them up before marking the ballot.",
    candidates: [

    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Education", office: "State Board of Education — two seats",
    note: "MICHIGAN ELECTS ITS EDUCATION BOARDS STATEWIDE, AND ALMOST NOBODY VOTES IN THEM — which is exactly the kind of race this site exists for. Two eight-year seats are up. Nominees are chosen at each party's fall state convention (MCL 168.282), which must meet at least 60 days before the election. Both Democratic incumbents were re-nominated. ⚠ Bipartisan bills would abolish elections for the three UNIVERSITY boards, though not for this one, starting in 2027. ⚠ Very little is published about most candidates for these boards; party and incumbency are usually the only decision-relevant facts a voter can get, and that is stated plainly on each card rather than padded.",
    candidates: [
      { name: "Judith Pritchett", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","Incumbent, re-nominated — these are eight-year terms","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Tiffany Tilley", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","Incumbent, re-nominated — these are eight-year terms","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Terence Collins", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Bree Moeggenberg", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Charles Essner", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "William Mohr II", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Christine C. Schwartz", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","Also appeared on the state's 2018 ballot for a statewide education board","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Wissam Charafeddine", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Green option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Green candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Mary Anne Hering", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Working Class nominee, chosen at the party's fall state convention","A recurring Working Class Party education-board candidate, including in 2018","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Working Class option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Working Class candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Kelli Monroe", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Natural Law nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Natural Law option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Natural Law candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Education", office: "University of Michigan Board of Regents — two seats",
    note: "TWO EIGHT-YEAR SEATS ON THE GOVERNING BOARD OF THE STATE'S FLAGSHIP UNIVERSITY, elected statewide and nominated at party conventions. ⚠ Only ONE incumbent is running: Paul Brown was re-nominated, while Regent Jordan Acker, elected in 2018, is NOT on the 2026 ballot — Amir Makled takes that slot. ⚠ Bipartisan legislation would abolish elections for this board starting in 2027, replacing them with appointments. Almost nothing is published about candidates for these seats.",
    candidates: [
      { name: "Paul Brown", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","Incumbent, re-nominated — these are eight-year terms","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Amir Makled", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","New nominee; he takes the slot of Regent Jordan Acker, who is not on the 2026 ballot","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Lena Epstein", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Michael Schostak", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Andrew Chadderdon", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Kyle Maas", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Education", office: "Michigan State University Board of Trustees — two seats",
    note: "TWO EIGHT-YEAR SEATS, elected statewide and nominated at party conventions. Both Democratic incumbents — Brianna Scott and Kelly Tebay Zemke — were re-nominated. ⚠ Bipartisan legislation would abolish elections for this board starting in 2027. This is the largest minor-party field of any Michigan education board, with ten candidates in total. Almost nothing is published about most of them.",
    candidates: [
      { name: "Brianna Scott", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","Incumbent, re-nominated — these are eight-year terms","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Kelly Tebay Zemke", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","Incumbent, re-nominated — these are eight-year terms","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Julie Maday", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Roger Victory", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Daniel R. Patterson", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Will Tyler White", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Janet Sanger", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","Also appeared on the state's 2018 ballot for a statewide education board","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "John Sanger", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","Also appeared on the state's 2018 ballot for a statewide education board","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "John Anthony La Pietra", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Green option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Green candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Yaz Ozbek", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Working Class nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Working Class option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Working Class candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Education", office: "Wayne State University Board of Governors — two seats",
    note: "TWO EIGHT-YEAR SEATS, elected statewide and nominated at party conventions. ⚠ NEITHER INCUMBENT IS RUNNING — the 2018 winners, Bryan Barnhill and Anil Kumar, are both off the 2026 ballot, so both Democratic nominees are new. (Kumar is instead running as an independent for Congress in MI-11.) ⚠ Bipartisan legislation would abolish elections for this board starting in 2027. Almost nothing is published about most candidates.",
    candidates: [
      { name: "Shereef Akeel", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","New nominee; neither 2018 incumbent is on the 2026 ballot","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Richard Mack", party: "D", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Democratic nominee, chosen at the party's fall state convention","New nominee; neither 2018 incumbent is on the 2026 ballot","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Andy Anuzis", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Christa Murphy", party: "R", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Republican nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["A major-party line is a realistic path on a ballot most voters mark by party","Michigan elects this board STATEWIDE, so every voter in the state has a say in it"],
        opponents: ["Board races sit near the bottom of a long ballot, where the party label does most of the deciding [Verify — structural argument]","No individual platform for this candidate could be located"] },
      { name: "Alex Avery", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Jami Van Alstine", party: "L", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Libertarian nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Libertarian option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Libertarian candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Jeff McDonald", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["U.S. Taxpayers nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a U.S. Taxpayers option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No U.S. Taxpayers candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Paul M. Ragan", party: "G", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Green nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Green option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Green candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Suzanne Roehrig", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Working Class nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Working Class option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Working Class candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] },
      { name: "Kathleen Oakford", party: "I", winner: false,
        positions: ["No published 2026 platform could be located [Verify — an absence of located records]","",""],
        differentiators: ["Natural Law nominee, chosen at the party's fall state convention","On the Secretary of State's certified November candidate list"],
        supporters: ["Gives voters a Natural Law option on a board the major parties otherwise split between them","Appears on the state's own certified ballot, so the choice is real rather than notional"],
        opponents: ["No Natural Law candidate has won a Michigan education-board seat in recent cycles [Verify — structural argument]","No individual platform or fundraising could be located"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Ballot Measure", office: "Proposal 2026-1 — Shall Michigan hold a constitutional convention?",
    note: "THIS QUESTION IS PUT TO MICHIGAN VOTERS AUTOMATICALLY EVERY 16 YEARS, AND THEY HAVE NEVER SAID YES — 1978, 1994 and 2010 all failed, the last of them 67%–33%. Official ballot language as placed before the Board of State Canvassers on July 24, 2026: 'A PROPOSAL TO CONVENE A CONSTITUTIONAL CONVENTION FOR THE PURPOSE OF DRAFTING A GENERAL REVISION OF THE STATE CONSTITUTION — Shall a convention of delegates, to be elected at a partisan special election, be convened in 2027 to draft a general revision of the State Constitution for presentation to the state's voters for their approval or rejection?' HOW IT WOULD WORK: one delegate for each of the 110 state House and 35 state Senate districts, elected at a special primary and general; the convention would convene Oct 5, 2027 in Lansing with no deadline to finish; anything it produced would go back to voters. ⚠ Final ballot certification is Sept 4, 2026 — this page is stated as of Sept 3.",
    candidates: [
      { name: "Yes — hold a constitutional convention", party: "I", winner: false,
        positions: ["Reopen the 1963 constitution to a general revision","Elect 145 delegates at a partisan special election in 2027","Send any resulting document back to voters for approval"],
        differentiators: ["Backed by House Speaker Matt Hall (R)","Backed by Senate Minority Leader Aric Nesbitt (R)","Appears automatically under the constitution's own 16-year clock, not by petition"],
        supporters: ["Hall argues too much has been stuffed into the constitution, pointing to voter-approved amendments such as marijuana legalisation and the redistricting commission","Nesbitt framed it as a chance to make updates Lansing lacks the political courage to make","Any product would still require voter approval, so the convention cannot change the constitution by itself"],
        opponents: ["A bipartisan coalition, Protect MI Constitution from Special Interests, is campaigning against it","Opponents cite tens of millions of dollars in taxpayer cost","Opponents argue special interests could capture an open-ended rewrite of the whole constitution"] },
      { name: "No — do not hold a constitutional convention", party: "I", winner: false,
        positions: ["Leave the 1963 constitution in place","Amend it through the existing petition and legislative routes instead","Avoid the cost and open-ended risk of a full rewrite"],
        differentiators: ["Backed by the bipartisan Protect MI Constitution from Special Interests coalition","Coalition members include Jeff Timmer, a former Michigan Republican Party executive director, and Dianne Byrom, a former Democratic House minority leader","On Sept 2, 2026 in Flint, former Republican Attorney General Bill Schuette and former Democratic Rep. Dan Kildee appeared together against it"],
        supporters: ["Schuette's argument, in his own words, is that it would be a circus and a podium for wannabe influencers","Michigan voters have rejected this question three times running, most recently by 67%–33%","Opponents argue an open convention invites well-funded interests to rewrite rights that currently have broad support"],
        opponents: ["Supporters answer that voters would still have to approve anything the convention produced","Critics of the 'no' campaign argue it protects a status quo that both parties' leaders have called unwieldy [Verify — structural argument]"] }
    ] },

  { date: "Nov 3, 2026", type: "upcoming", scope: "State · Statewide · Ballot Measure", office: "Money Out of Politics — a proposed initiated law on campaign finance",
    note: "IT IS ON THE BALLOT, AND THE LEGISLATURE HAD ITS CHANCE TO PASS IT INSTEAD. The Board of State Canvassers certified the petition 3–1 on July 24, 2026 — 368,762 valid signatures estimated against 356,958 required. Under Michigan's initiated-law process the Legislature could then have enacted it directly: the HOUSE PASSED IT 77–26 on Aug 25, 2026, but the SENATE DECLINED TO TAKE IT UP, so it goes to voters. ⚠ THE PROPOSAL NUMBER IS NOT FINAL. The Board's drafts labelled it 'Proposal 2026-2 or 2026-3' because the designation depended on whether a separate citizenship-voting amendment also certified; it did not, so this should become Proposal 2026-2 — but that is confirmed only at the Sept 4, 2026 certification [Verify]. OFFICIAL 100-WORD SUMMARY as drafted by the Director of Elections: the proposal would prohibit regulated electric and gas utilities, contractors with over $250,000 annually in government contracts, and people and organisations with substantial connections to them, from making direct or indirect campaign contributions to those who run for or hold offices that affect them; expand laws regulating spending on political communications, including donor-disclosure requirements, to cover communications that clearly identify candidates or ballot questions even without express advocacy; and expressly apply the paid-for disclosure requirement to internet political communications. ⚠ LIVE LITIGATION: Protect MI Free Speech sued in the Michigan Supreme Court on Aug 4, 2026 arguing the Bureau used a faulty statistical formula; as of Sept 3 no oral argument had been scheduled and no resolution was reported [Verify].",
    candidates: [
      { name: "Yes — adopt the initiated law", party: "I", winner: false,
        positions: ["Bar campaign contributions from regulated utilities and large government contractors","Extend donor-disclosure rules to communications that identify a candidate without expressly advocating a vote","Apply paid-for disclosure requirements to internet political communications"],
        differentiators: ["Certified by the Board of State Canvassers 3–1 on July 24, 2026","Passed the Michigan House 77–26 on Aug 25, 2026","Coalition co-chaired by Christy McGillivray of Voters Not Politicians and Sean McBrearty"],
        supporters: ["McGillivray describes it as attacking the actual rot in Michigan politics, and McBrearty cites a pattern of corruption from utility spending","A 2025 Bridge Michigan analysis found House members average just 14% of their funds from their own constituents, and that in 2023, 119 of 148 legislators took utility PAC money","Michigan had more power outages in 2023 than any other state while carrying the 14th-highest residential electricity prices"],
        opponents: ["Protect MI Free Speech, backed by utilities and Blue Cross Blue Shield, calls it a large expansion of government regulation over speech and association","Critics note it does NOT restrict unions or advocacy groups on either side","Its own largest single donor is a progressive dark-money nonprofit, All Hands on Deck, which gave $5.4 million of the $7.4 million raised"] },
      { name: "No — reject the initiated law", party: "I", winner: false,
        positions: ["Leave Michigan's existing campaign-finance law unchanged","Avoid new disclosure duties on issue communications that do not expressly advocate a vote","Leave the question of utility political spending to the Legislature"],
        differentiators: ["Campaign run by Protect MI Free Speech, backed by utilities and Blue Cross Blue Shield","Spokesperson John Sellek argues many attorneys believe it would not survive review","The Michigan Senate declined to enact the law when it had the chance"],
        supporters: ["Sellek's argument is that the measure would not pass constitutional muster after Citizens United","Opponents argue it regulates speech asymmetrically, leaving unions and advocacy groups untouched","A pending Michigan Supreme Court challenge argues the Bureau's signature-validity formula was faulty"],
        opponents: ["Supporters answer that the utilities funding the opposition are the entities the measure would restrict","The House passed the same text 77–26, which undercuts the argument that it is unworkable [Verify — structural argument]"] }
    ] }
];
