// Florida U.S. House districts 15-21 — HB 1D lines. The Aug 18, 2026 primary was CERTIFIED
// Aug 27, 2026 by the Florida Elections Canvassing Commission (Gov. DeSantis, AG Uthmeier,
// Agriculture Commissioner Simpson).
// ⚠ CORRECTED AT BUILD TIME: the researcher reported that no post-HB 1D PVI existed. That was WRONG.
// Cook HAS recalculated PVI on the new lines and publishes it in its own Datawrapper files, chart
// `fejB0` (and the fuller `rAx2t`, which also carries raw 2020/2024 presidential vote by district).
// Every PVI below was read from `rAx2t` directly. Chart `vcf6i` is the OLD 2025 file — do not use it
// for Florida. Two other district agents found the 2026 file independently and agreed exactly.
// ⚠ Sabato and Inside Elections ratings could NOT be read at the raters' own sites and are
// therefore NOT carded. Cook's Aug 25, 2026 House ratings PDF WAS read at cookpolitical.com.
  15: { name: "U.S. House — FL District 15", region: "Eastern Hillsborough north through Pasco, plus all of Hernando and Citrus counties",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "REDRAWN UNDER HB 1D — DISTRICT 15 NOW RUNS FROM THE TAMPA SUBURBS NORTH THROUGH ALL OF HERNANDO AND CITRUS COUNTIES, absorbing much of the old District 12 and adding Citrus outright. ✅ Incumbent Laurel Lee chose to run in the renumbered seat and drew no primary opponent. ⚠ Cook does not list FL-15 among its competitive races as of Aug 25, 2026 — i.e. Solid R. ✅ COOK HAS RECALCULATED PVI ON THE NEW LINES: FL-15 is now R+9, up from R+5 on the old map, so the redraw made this seat four points MORE Republican. Aug 18 primary results were certified Aug 27, 2026.",
        candidates: [
          { name: "Laurel Lee (incumbent)", party: "R", winner: false,
            positions: ["Securing the border", "Growing the economy and leading in innovation", "Crime and community safety; supporting military and veterans"],
            differentiators: ["Incumbent U.S. Representative, FL-15", "Unopposed in the Aug 18 Republican primary", "$1,943,656 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by Donald Trump, AIPAC and Maggie's List"],
            supporters: ["Trump endorsement in a district Cook does not rate competitive", "Roughly a thousand-to-one cash advantage over her opponent", "Ran unopposed for renomination — no intraparty challenge to her record"],
            opponents: ["Critics tie her safety to a mid-decade map drawn to entrench Republicans rather than to her own margin [Verify — structural argument]", "Has not faced a competitive general election [Verify — structural argument]"] },
          { name: "Robert People", party: "D", winner: false,
            positions: ["Affordability and Social Security", "Healthcare and clean energy", "Takes no AIPAC money; opposes arms shipments to Israel"],
            differentiators: ["Retired U.S. Army veteran and writer", "Won the Aug 18 Democratic primary with 53.6%", "$1,926 cash on hand as of March 31, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Beat a better-funded CIA-veteran rival, which is a real grassroots signal", "An explicit anti-AIPAC, anti-arms-transfer platform gives the left a clear alternative", "A veteran outsider with no ties to the party establishment"],
            opponents: ["Effectively unfunded against a $1.9M incumbent [Verify — structural argument]", "Long odds in a seat Cook does not rate competitive [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "ROBERT PEOPLE WON A CLOSE TWO-WAY DEMOCRATIC PRIMARY, 53.6% TO 46.4%, on the new district lines. The Republican primary was uncontested and is not carded. Certified Aug 27, 2026.",
        candidates: [
          { name: "Robert People", party: "D", winner: true, positions: [], differentiators: ["22,213 votes — 53.6%"], supporters: [], opponents: [] },
          { name: "Chris Irizarry", party: "D", winner: false, positions: [], differentiators: ["19,196 votes — 46.4%", "Retired CIA officer and Army veteran; previously ran in the 12th district"], supporters: [], opponents: [] } ] } ] },
  16: { name: "U.S. House — FL District 16", region: "Manatee, DeSoto and Hardee counties plus parts of Pinellas, Polk, Sarasota and Hillsborough",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "OPEN SEAT — 18-YEAR INCUMBENT VERN BUCHANAN IS NOT SEEKING RE-ELECTION, and HB 1D stretched the district east and west from its old Manatee/Brandon core to pick up parts of Pinellas, Polk and Sarasota plus all of DeSoto and Hardee. ✅ Sydney Gruters won the Republican nomination with 63.4% after Trump moved his endorsement from Buchanan to her. ⚠ Cook does not list FL-16 among its competitive races as of Aug 25, 2026 (Solid R), and its recalculated 2026 PVI is R+6, barely moved from R+7. Other raters are reported to see an open-seat opening, but neither Sabato nor Inside Elections could be read at their own sites, so no second rating is carded [Verify]. Certified Aug 27, 2026.",
        candidates: [
          { name: "Sydney Gruters", party: "R", winner: false,
            positions: ["Lower the cost of living for area families", "Cut taxes and regulations", "America First framing — 'defend the American way of life'"],
            differentiators: ["Former executive director of the New College of Florida Foundation", "Won the Aug 18 Republican primary with 63.4%", "$622,381 cash on hand as of July 29, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by Donald Trump, Sen. Rick Scott, Speaker Mike Johnson and all seven area sheriffs"],
            supporters: ["Consolidated the whole party apparatus — Trump, House leadership and every sheriff in the district", "63% in a three-way primary is a commanding mandate", "An open-seat Republican in territory Cook does not rate competitive"],
            opponents: ["Her opponent's campaign brands her the 'Gruters cronyism machine,' arguing her rise rests on her husband Joe Gruters' RNC chairmanship", "Has never held elected office [Verify — no prior office located in official candidate records]"] },
          { name: "Kelly Kirschner", party: "D", winner: false,
            positions: ["Water, growth and natural-resource decisions judged by who they actually help", "Affordability as opportunity, not just prices", "Disaster readiness and the property-insurance crisis; support for small business"],
            differentiators: ["Former mayor of Sarasota; former vice president and dean at Eckerd College", "Won a five-way Democratic primary with 43.0%", "$80,738 cash on hand as of July 29, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by the Florida AFL-CIO and former St. Petersburg mayor Rick Kriseman"],
            supporters: ["The only candidate in the race with executive elected experience", "Insurance and water quality are top-tier pocketbook issues on this coast", "An open seat on brand-new lines is the party's best structural shot here in years"],
            opponents: ["Outraised roughly eight to one on cash on hand", "Cook does not rate the seat competitive, so national money may never arrive [Verify — structural argument]"] },
          { name: "Mark Davis", party: "I", winner: false,
            positions: ["⚠ His site lists the communities he would serve rather than detailed policy planks [Verify]", "Runs explicitly outside both major parties", "A U.S. Air Force veteran framing service over party"],
            differentiators: ["U.S. Air Force veteran", "Qualified NPA candidate on the November ballot", "$691 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Gives voters a ballot option in a seat where the general is not rated competitive", "A veteran running with no party machine behind him"],
            opponents: ["Under $1,000 on hand against a $622K nominee [Verify — structural argument]", "No detailed policy platform could be located on his campaign site"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "SYDNEY GRUTERS WON THE OPEN-SEAT REPUBLICAN PRIMARY OUTRIGHT WITH 63.4%. ⚠ Trump had originally endorsed retiring incumbent Vern Buchanan, then switched to Gruters. Certified Aug 27, 2026.",
        candidates: [
          { name: "Sydney Gruters", party: "R", winner: true, positions: [], differentiators: ["48,570 votes — 63.4%"], supporters: [], opponents: [] },
          { name: "Eddie Speir", party: "R", winner: false, positions: [], differentiators: ["16,291 votes — 21.3%", "Former New College of Florida trustee; 2024 candidate for this district"], supporters: [], opponents: [] },
          { name: "Ed Pope", party: "R", winner: false, positions: [], differentiators: ["11,692 votes — 15.3%", "Businessman and Navy veteran"], supporters: [], opponents: [] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "KELLY KIRSCHNER WON A FIVE-WAY DEMOCRATIC PRIMARY WITH 43.0%, more than double the runner-up. Certified Aug 27, 2026.",
        candidates: [
          { name: "Kelly Kirschner", party: "D", winner: true, positions: [], differentiators: ["23,488 votes — 43.0%"], supporters: [], opponents: [] },
          { name: "Tamika Lyles", party: "D", winner: false, positions: [], differentiators: ["10,888 votes — 19.9%", "Nonprofit founder; 2020 candidate for Florida House District 43"], supporters: [], opponents: [] },
          { name: "Jan Schneider", party: "D", winner: false, positions: [], differentiators: ["8,423 votes — 15.4%", "Attorney; party nominee for this district in 2016, 2022 and 2024"], supporters: [], opponents: [] },
          { name: "Jon Harris", party: "D", winner: false, positions: [], differentiators: ["6,856 votes — 12.5%", "U.S. Army veteran"], supporters: [], opponents: [] },
          { name: "Glenn Pearson", party: "D", winner: false, positions: [], differentiators: ["5,002 votes — 9.2%", "Small-business owner; 2024 Manatee County commission candidate"], supporters: [], opponents: [] } ] } ] },
  17: { name: "U.S. House — FL District 17", region: "Coastal Sarasota and Charlotte counties plus part of Lee County including Fort Myers",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "MODESTLY REDRAWN UNDER HB 1D — DISTRICT 17 DROPPED INLAND EASTERN SARASOTA COUNTY AND PICKED UP MORE OF FORT MYERS IN LEE COUNTY. ✅ Incumbent Greg Steube is running in the same seat and was unopposed for renomination. ⚠ Cook does not list FL-17 among its competitive races as of Aug 25, 2026 — Solid R; its recalculated 2026 PVI is R+10, essentially unmoved from R+11. Certified Aug 27, 2026.",
        candidates: [
          { name: "Greg Steube (incumbent)", party: "R", winner: false,
            positions: ["⚠ He runs as a 'trusted conservative' and Army veteran; his campaign site publishes no issues page, so no itemised platform could be documented [Verify]", "", ""],
            differentiators: ["Incumbent U.S. Representative, FL-17", "Unopposed in the Aug 18 Republican primary", "$2,166,212 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by Donald Trump and AIPAC"],
            supporters: ["Trump endorsement and no primary opposition", "A $2.2M war chest, roughly seventy times his opponent's", "The seat is not rated competitive by Cook"],
            opponents: ["His campaign site offers voters no detailed policy platform to evaluate", "Critics argue a safe seat leaves him unaccountable to a general electorate [Verify — structural argument]"] },
          { name: "Matthew Montavon", party: "D", winner: false,
            positions: ["Defending democracy", "Lowering costs", "Reforming immigration"],
            differentiators: ["Was the Democratic candidate for this district in 2024", "Won the Aug 18 Democratic primary with 55.4%", "$29,947 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["A second run at the seat gives him name recognition and an existing volunteer base", "Won his primary by nearly eleven points", "Publishes a clearer issue platform than the incumbent does"],
            opponents: ["Outgunned roughly seventy to one on cash [Verify — structural argument]", "Long odds in a seat no major rater treats as competitive [Verify — structural argument]"] },
          { name: "Michael J. Quirk", party: "I", winner: false,
            positions: ["⚠ No published policy platform could be located — no campaign site was found [Verify]", "", ""],
            differentiators: ["Qualified NPA candidate on the November ballot", "$11,552 raised and $4,592 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Offers an alternative to voters unwilling to back either major party", "Filed and qualified under his own steam with no party support"],
            opponents: ["No campaign presence could be located [Verify — an absence of located records]", "Under $5,000 on hand against a $2.2M incumbent [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "MATTHEW MONTAVON WON THE DEMOCRATIC PRIMARY 55.4% TO 44.6%. The Republican primary was uncontested and is not carded. Certified Aug 27, 2026.",
        candidates: [
          { name: "Matthew Montavon", party: "D", winner: true, positions: [], differentiators: ["27,627 votes — 55.4%"], supporters: [], opponents: [] },
          { name: "Allen L. Spence Jr.", party: "D", winner: false, positions: [], differentiators: ["22,270 votes — 44.6%", "Equities trader"], supporters: [], opponents: [] } ] } ] },
  18: { name: "U.S. House — FL District 18", region: "Polk County plus part of Osceola County",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "SUBSTANTIALLY REDRAWN — HB 1D COLLAPSED DISTRICT 18 FROM A SPRAWLING RURAL MULTI-COUNTY SEAT INTO A COMPACT DISTRICT ANCHORED IN POLK COUNTY plus a slice of Osceola. ✅ Incumbent Scott Franklin of Lakeland is running in the redrawn seat. ✅ NEITHER PRIMARY WAS CONTESTED — all three November candidates advanced without a primary fight, so no Aug 18 race is carded. ⚠ Cook does not list FL-18 among its competitive races as of Aug 25, 2026 — Solid R — but the collapse into Polk moved its PVI SIX POINTS, from R+14 on the old sprawling seat to R+8 on the new one.",
        candidates: [
          { name: "Scott Franklin (incumbent)", party: "R", winner: false,
            positions: ["Fuelling economic growth and advancing a conservative agenda", "Fighting socialism and protecting constitutional rights", "Standing up for Christian values; strengthening national security"],
            differentiators: ["Incumbent U.S. Representative; based in Lakeland, the new district's population centre", "Unopposed in the Aug 18 Republican primary", "$945,704 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by AIPAC and Associated Builders and Contractors Florida Gulf Coast"],
            supporters: ["Lives in and already represents the Polk County core the new map hands him", "Nearly $1M banked against an opponent reporting three figures", "No primary challenge to his conservative record"],
            opponents: ["Benefits from a mid-decade redraw rather than from a verdict by voters [Verify — structural argument]", "Faces no rated competition, which limits the pressure to engage the district [Verify — structural argument]"] },
          { name: "Curtis Gibson", party: "D", winner: false,
            positions: ["Property-insurance stability and property-tax relief", "Veterans' healthcare access", "Citrus and agriculture; infrastructure that keeps up with growth"],
            differentiators: ["Former Lake Wales city commissioner", "Unopposed in the Aug 18 Democratic primary", "$348 cash on hand as of March 31, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Local elected experience inside the new Polk-centred district", "Runs on insurance, property taxes and citrus — concrete Heartland pocketbook issues", "Cleared the primary field without spending on a contest"],
            opponents: ["Reported under $400 on hand against a $945,000 incumbent [Verify — structural argument]", "Long odds in a seat no major rater treats as competitive [Verify — structural argument]"] },
          { name: "Deva Simmons", party: "I", winner: false,
            positions: ["Affordable healthcare and quality education", "Economic stability", "Defending democracy and ending partisan gerrymandering"],
            differentiators: ["Developmental therapist", "Qualified NPA candidate on the November ballot", "$5,764 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Her anti-gerrymandering message lands directly on the HB 1D redraw that reshaped this seat", "Offers unaffiliated voters a ballot option in a one-sided district"],
            opponents: ["Under $6,000 on hand and no party infrastructure [Verify — structural argument]", "NPA candidates rarely clear low single digits in Florida U.S. House races [Verify — structural argument]"] } ] } ] },
  19: { name: "U.S. House — FL District 19", region: "Inland Collier County and part of Lee County, anchored on Naples — Fort Myers removed",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "OPEN SEAT — INCUMBENT BYRON DONALDS VACATED IT TO RUN FOR GOVERNOR, AND HE WON THE AUG 18 REPUBLICAN GUBERNATORIAL PRIMARY. HB 1D also redrew the district, dropping Fort Myers and pushing inland into Collier. ✅ THE AUG 18 REPUBLICAN PRIMARY WAS A NATIONAL STORY: Trump endorsed Catalina Lauf on Aug 13, five days before the vote, and she LOST to broadcaster Jim Schwartzel 29.1% to 22.0% in a ten-candidate field that also drew former congressmen Madison Cawthorn and Chris Collins from other states. ⚠ Cook does not list FL-19 among its competitive races as of Aug 25, 2026 — Solid R, and its PVI is R+14 both before and after the redraw. Certified Aug 27, 2026.",
        candidates: [
          { name: "Jim Schwartzel", party: "R", winner: false,
            positions: ["Back Trump's America First agenda — energy independence, border enforcement, law and order", "Congressional term limits", "Protect Southwest Florida water quality — the Caloosahatchee, beaches and estuaries"],
            differentiators: ["President of Sun Broadcasting; founder of 92.5 FOX News Radio in Fort Myers", "Won the ten-way Aug 18 Republican primary with 29.1%, beating Trump's endorsee", "$181,899 cash on hand as of July 29, 2026 after spending $1.88M of $2.07M raised [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by Jim Jordan, Lauren Boebert, Connie Mack III and IV, and Turning Point Action"],
            supporters: ["Won without — and against — the Trump endorsement, which shows an independent local base built over years of radio", "Owns the district's conservative media megaphone and its audience", "Nominee in a seat Cook does not rate competitive"],
            opponents: ["Spent 91% of everything he raised to win the primary, leaving him comparatively thin for the general [Verify — structural argument]", "Beat Trump's pick, which critics say leaves him without the President's active backing in a MAGA-heavy district [Verify — structural argument]", "No prior elected office [Verify — no prior office located in official candidate records]"] },
          { name: "Victor Arias", party: "D", winner: false,
            positions: ["⚠ No policy platform could be retrieved — his campaign site was returning a server error throughout this research [Verify]", "", ""],
            differentiators: ["Attorney", "Won the Aug 18 Democratic primary with 45.5% in a three-way race", "$11,963 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Won a genuine three-way contested primary rather than being handed the nomination", "Faces a Republican who emptied his treasury and lost the President's endorsement", "An attorney's background in a race otherwise short on policy detail"],
            opponents: ["Roughly $12,000 on hand in an expensive Fort Myers–Naples media market [Verify — structural argument]", "His campaign website was offline during this research and no platform could be documented", "The seat is not rated competitive by any major rater [Verify — structural argument]"] },
          { name: "Seth Haskin", party: "I", winner: false,
            positions: ["Strict constitutionalism", "Rule of law", "Transparency and simplicity in government; independence and self-governance"],
            differentiators: ["Business manager", "Qualified NPA candidate on the November ballot", "$775 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["Publishes a coherent constitutionalist platform in a race where the Democrat's site is down", "An open seat and a fractured ten-way Republican primary leave more unattached voters than usual"],
            opponents: ["Under $1,000 on hand [Verify — structural argument]", "No organisational or party support could be located [Verify — an absence of located records]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "JIM SCHWARTZEL WON A TEN-CANDIDATE OPEN-SEAT PRIMARY WITH 29.1%, DEFEATING TRUMP-ENDORSED CATALINA LAUF. ✅ Trump endorsed Lauf on Aug 13, only five days before the election. ⚠ The field included two former congressmen from other states — Madison Cawthorn of North Carolina and Chris Collins of New York — plus former Illinois state senator Jim Oberweis, who spent $3.08M to finish third. Certified Aug 27, 2026.",
        candidates: [
          { name: "Jim Schwartzel", party: "R", winner: true, positions: [], differentiators: ["26,153 votes — 29.1%"], supporters: [], opponents: [] },
          { name: "Catalina Lauf", party: "R", winner: false, positions: [], differentiators: ["19,722 votes — 22.0%", "Trump-endorsed Aug 13, 2026; former Commerce Department adviser and 2022 nominee in IL-11"], supporters: [], opponents: [] },
          { name: "Jim Oberweis", party: "R", winner: false, positions: [], differentiators: ["14,110 votes — 15.7%", "Former Illinois state senator and Oberweis Dairy chairman; spent $3.08M"], supporters: [], opponents: [] },
          { name: "Madison Cawthorn", party: "R", winner: false, positions: [], differentiators: ["7,596 votes — 8.5%", "Former U.S. representative from NC-11 (2021–2023)"], supporters: [], opponents: [] },
          { name: "Chris Collins", party: "R", winner: false, positions: [], differentiators: ["6,617 votes — 7.4%", "Former U.S. representative from NY-27 (2013–2019)"], supporters: [], opponents: [] },
          { name: "Mike Pedersen", party: "R", winner: false, positions: [], differentiators: ["5,581 votes — 6.2%", "Marine Corps veteran"], supporters: [], opponents: [] },
          { name: "John Strand", party: "R", winner: false, positions: [], differentiators: ["3,513 votes — 3.9%"], supporters: [], opponents: [] },
          { name: "Ola Hawatmeh", party: "R", winner: false, positions: [], differentiators: ["2,534 votes — 2.8%"], supporters: [], opponents: [] },
          { name: "Greg 'Tex' Bukowski", party: "R", winner: false, positions: [], differentiators: ["2,266 votes — 2.5%", "Sarasota County Charter Review Board member"], supporters: [], opponents: [] },
          { name: "Linda J. Sawyer", party: "R", winner: false, positions: [], differentiators: ["1,650 votes — 1.8%"], supporters: [], opponents: [] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "VICTOR ARIAS WON A CLOSE THREE-WAY DEMOCRATIC PRIMARY, 45.5% TO 41.1%. Certified Aug 27, 2026.",
        candidates: [
          { name: "Victor Arias", party: "D", winner: true, positions: [], differentiators: ["15,410 votes — 45.5%"], supporters: [], opponents: [] },
          { name: "Howard Sapp", party: "D", winner: false, positions: [], differentiators: ["13,918 votes — 41.1%", "Retired air traffic controller; 2024 nominee for Florida House District 78"], supporters: [], opponents: [] },
          { name: "Robert M. Neeld", party: "D", winner: false, positions: [], differentiators: ["4,553 votes — 13.4%", "2016 nominee for this district"], supporters: [], opponents: [] } ] } ] },
  20: { name: "U.S. House — FL District 20", region: "A compact central and northern Broward County district including Margate and Oakland Park",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "THE BIGGEST REDISTRICTING STORY IN THIS BLOC — HB 1D REBUILT DISTRICT 20 FROM A SPRAWLING MULTI-COUNTY SHAPE INTO A COMPACT BROWARD SEAT, AND FIVE-TERM CONGRESSWOMAN DEBBIE WASSERMAN SCHULTZ MOVED HERE FROM DISTRICT 25 AND WON THE PRIMARY. ⚠ The seat is currently VACANT: the prior incumbent, Sheila Cherfilus-McCormick, resigned Apr 21, 2026 minutes before a House Ethics sanction hearing, after a Nov 2025 federal indictment alleging theft of $5M in FEMA funds; she ran anyway and finished FOURTH with 9.2%. Her criminal trial is reported for February 2027 [Verify — a press report, not a court docket]. ⚠ Cook does not list FL-20 among its competitive races as of Aug 25, 2026 — Solid D; its recalculated 2026 PVI is D+20, down slightly from D+22. Certified Aug 27, 2026.",
        candidates: [
          { name: "Debbie Wasserman Schultz (incumbent, currently FL-25)", party: "D", winner: false,
            positions: ["⚠ Her campaign runs on a record rather than an itemised platform [Verify]", "Reproductive rights — endorsed by Planned Parenthood Action Fund", "Gun safety (Giffords) and conservation (League of Conservation Voters)"],
            differentiators: ["Incumbent U.S. Representative for FL-25; former Democratic National Committee chair", "Won the five-way Aug 18 Democratic primary with 45.3%", "$1,861,373 cash on hand as of July 29, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by the Florida AFL-CIO, Broward Teachers Union, Giffords, LCV and Planned Parenthood Action Fund"],
            supporters: ["Won a commanding plurality against four opponents including a sitting member and a former county mayor", "Deep labour, environmental and reproductive-rights institutional backing", "$1.86M on hand — roughly forty times the Republican nominee"],
            opponents: ["Critics call her a carpetbagger who switched districts rather than face the redrawn FL-25", "House Minority Leader Hakeem Jeffries and the Florida LGBTQ Democratic Caucus both declined to endorse in this primary", "Progressives argue a former DNC chair displacing this district's field is a step backward on representation [Verify — structural argument]"] },
          { name: "Brent Andersen", party: "R", winner: false,
            positions: ["⚠ He runs as a 'Conservative Republican | Builder'; his site publishes no itemised issue platform [Verify]", "", ""],
            differentiators: ["Businessman", "Won the Aug 18 Republican primary with 53.8%", "$46,553 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by state Rep. Chip LaMarca, Log Cabin Republicans and the Sun Sentinel"],
            supporters: ["Won a majority in a four-way primary on modest spending", "The Sun Sentinel endorsement and Log Cabin Republicans backing signal broader-than-base appeal", "Faces a Democratic nominee under carpetbagger attack in a seat she has never represented"],
            opponents: ["Cook rates the seat Solid D at a 2026 PVI of D+20 [Verify — structural argument]", "$46,553 against $1.86M is not a competitive general-election budget [Verify — structural argument]", "Publishes no detailed policy platform for voters to evaluate"] },
          { name: "Kedner Maxime", party: "I", winner: false,
            positions: ["Affordability and lower inflation", "Healthcare as a right; world-class education in every zip code", "Secure borders with a humane path forward; TPS protections for Haiti"],
            differentiators: ["Runs as 'Dr. Kedner Maxime' on a service-over-politics platform", "Advanced unopposed as the NPA candidate on the November ballot", "$2,541 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["His TPS-for-Haiti advocacy speaks directly to Broward's large Haitian-American community, which the departing incumbent represented", "Publishes a fuller issue platform than the Republican nominee", "Offers a non-major-party option after a bruising, scandal-shadowed Democratic primary"],
            opponents: ["Under $3,000 on hand against a $1.86M nominee [Verify — structural argument]", "No institutional or party support could be located [Verify — an absence of located records]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "DEBBIE WASSERMAN SCHULTZ WON WITH 45.3% AFTER SWITCHING FROM DISTRICT 25 — AND THE PRIOR INCUMBENT, SHEILA CHERFILUS-MCCORMICK, FINISHED FOURTH WITH 9.2%. ⚠ Cherfilus-McCormick had already resigned the seat on Apr 21, 2026 ahead of a House Ethics sanction hearing, following a federal indictment over $5M in FEMA funds, and reported $0 cash on hand. Certified Aug 27, 2026.",
        candidates: [
          { name: "Debbie Wasserman Schultz", party: "D", winner: true, positions: [], differentiators: ["30,505 votes — 45.3%"], supporters: [], opponents: [] },
          { name: "Dale V.C. Holness", party: "D", winner: false, positions: [], differentiators: ["15,571 votes — 23.1%", "Former mayor of Broward County; 2022 candidate for this seat"], supporters: [], opponents: [] },
          { name: "Elijah Manley", party: "D", winner: false, positions: [], differentiators: ["9,377 votes — 13.9%", "Substitute teacher and activist; raised $1.07M"], supporters: [], opponents: [] },
          { name: "Sheila Cherfilus-McCormick", party: "D", winner: false, positions: [], differentiators: ["6,193 votes — 9.2%", "Former U.S. representative (2022–2026); resigned Apr 21, 2026 amid a federal indictment"], supporters: [], opponents: [] },
          { name: "Luther 'Uncle Luke' Campbell", party: "D", winner: false, positions: [], differentiators: ["5,691 votes — 8.5%", "Rapper; 2011 candidate for mayor of Miami-Dade County"], supporters: [], opponents: [] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "BRENT ANDERSEN WON THE FOUR-WAY REPUBLICAN PRIMARY WITH 53.8%. Certified Aug 27, 2026.",
        candidates: [
          { name: "Brent Andersen", party: "R", winner: true, positions: [], differentiators: ["7,442 votes — 53.8%"], supporters: [], opponents: [] },
          { name: "Rod Joseph", party: "R", winner: false, positions: [], differentiators: ["2,831 votes — 20.5%"], supporters: [], opponents: [] },
          { name: "Carla Spalding", party: "R", winner: false, positions: [], differentiators: ["2,701 votes — 19.5%"], supporters: [], opponents: [] },
          { name: "Lateresa 'LA' Jones", party: "R", winner: false, positions: [], differentiators: ["866 votes — 6.3%"], supporters: [], opponents: [] } ] } ] },
  21: { name: "U.S. House — FL District 21", region: "Martin, St. Lucie and Indian River counties plus northern Palm Beach County (Jupiter, Palm Beach Gardens)",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "REDRAWN UNDER HB 1D — DISTRICT 21 SHED INLAND NORTHERN PALM BEACH COUNTY AND ADDED INDIAN RIVER COUNTY, keeping its Martin and St. Lucie core and the Jupiter–Palm Beach Gardens coast. ✅ Incumbent Brian Mast is running in the same seat and was unopposed for renomination. ✅ The Democratic primary was decided by 362 votes out of 47,746 — 50.4% to 49.6%. ⚠ Cook does not list FL-21 among its competitive races as of Aug 25, 2026 — Solid R, and its PVI is R+7 both before and after the redraw. Certified Aug 27, 2026.",
        candidates: [
          { name: "Brian Mast (incumbent)", party: "R", winner: false,
            positions: ["America First; 'drain the swamp'", "Clean water — Lake Okeechobee discharges and estuary health", "Tax cuts and jobs; veterans' and seniors' care; Second Amendment; support for Israel"],
            differentiators: ["Incumbent U.S. Representative, FL-21; Army veteran", "Unopposed in the Aug 18 Republican primary", "$2,928,458 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by Donald Trump and AIPAC"],
            supporters: ["Nearly $2.9M banked — over fifteen times his opponent", "An Army veteran with a long-standing clean-water record that crosses party lines locally", "Trump endorsement and no primary opposition"],
            opponents: ["His opponent's campaign publicly accuses him of ducking debates", "Both a pro-AIPAC tracker and an anti-AIPAC PAC engaged in this race, making his Israel positioning a live local issue", "Critics say the new lines added friendly Indian River territory while dropping less favourable Palm Beach precincts [Verify — structural argument]"] },
          { name: "James T. Martin", party: "D", winner: false,
            positions: ["Cost of living; protecting Social Security and veterans' benefits", "Clean water", "Anti-corruption and transparency; healthcare; immigration"],
            differentiators: ["Lieutenant commander, U.S. Coast Guard Reserve", "Won the Aug 18 Democratic primary by 362 votes — 50.4% to 49.6%", "$188,041 cash on hand as of July 29, 2026 [Verify — an FEC-cited table, not read at the FEC]", "Endorsed by former Vice President Kamala Harris, the Palm Beach Post, Moms Demand Action and End Citizens United"],
            supporters: ["A Coast Guard officer running on clean water in a district defined by Lake Okeechobee discharges", "Palm Beach Post endorsement plus national validators including Kamala Harris", "The best-funded Democrat this seat has fielded in years at $188K on hand"],
            opponents: ["Won his own primary by under 400 votes, which exposes a divided Democratic base", "Outspent roughly fifteen to one by the incumbent [Verify — structural argument]", "Cook does not rate the seat competitive [Verify — structural argument]"] },
          { name: "Alexander Cooke", party: "I", winner: false,
            positions: ["Florida homeowner affordability and the property-insurance crisis", "Protect wild Florida; stop Lake Okeechobee discharges", "Hold Washington accountable — no party, no corporate PACs"],
            differentiators: ["Former mayor and councilmember of Juno Beach", "Qualified NPA candidate on the November ballot", "$19,543 raised — $13,000 of it self-funded — and $665 cash on hand as of June 30, 2026 [Verify — an FEC-cited table, not read at the FEC]"],
            supporters: ["The only candidate in the race with local municipal executive experience in the district", "A detailed, locally specific platform on insurance, the ACA premium cliff and Okeechobee discharges", "A no-corporate-PAC pledge appeals to voters alienated by both parties"],
            opponents: ["$665 on hand against a $2.9M incumbent, and two-thirds of what he raised was his own money [Verify — structural argument]", "NPA candidates rarely clear low single digits in Florida congressional races [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "JAMES MARTIN WON BY 362 VOTES — 50.4% TO 49.6% — one of the closest congressional primaries in the state. ⚠ Bernard Taylor actually OUTRAISED Martin, $993,380 to $579,000, and still lost. The Republican primary was uncontested and is not carded. Certified Aug 27, 2026.",
        candidates: [
          { name: "James T. Martin", party: "D", winner: true, positions: [], differentiators: ["24,054 votes — 50.4%"], supporters: [], opponents: [] },
          { name: "Bernard Taylor", party: "D", winner: false, positions: [], differentiators: ["23,692 votes — 49.6%", "Firefighter; raised $993,380 — more than the winner"], supporters: [], opponents: [] } ] } ] },
