// Florida U.S. House districts 8-14 — HB 1D lines. Aug 18, 2026 primary CERTIFIED Aug 27, 2026.
// ✅ ALL SEVEN of these districts were redrawn. Cook recalculated PVI on the new lines and the
// shifts here are the largest in the state: FL-8 R+11->R+8, FL-9 D+4->R+8 (the biggest partisan
// swing in Florida), FL-10 D+13 unchanged, FL-11 R+8->R+7, FL-12 R+17->R+7, FL-13 R+5->R+6,
// FL-14 D+5->R+4 (the largest raw-PVI shift in the state, -11.1). Every value here was
// re-read at build time from Cook's own Datawrapper file `rAx2t` and matches.
// ⚠ Money figures are the July 29, 2026 FEC pre-primary report — post-primary numbers are not due
// until the October quarterly, so primary spending is NOT reflected.
// ⚠ Sabato publishes House ratings as IMAGES and could not be read; Inside Elections was read from
// its own public ratings API. No rating here is taken from an aggregator.
// ⚠ Write-in candidates (FL-14: Salomon Hernandez, Keith Varian) are state-certified but do NOT
// appear on the printed ballot, so they are noted in the race note rather than carded.
  8: { name: "U.S. House — FL District 8", region: "Brevard County's Space Coast plus the UCF area of eastern Orange County",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "REDISTRICTING MADE THIS SEAT MEASURABLY CLOSER: HB 1D dropped Indian River County and pushed FL-8 west to absorb about 160,000 more Orange County residents, moving Cook's PVI from R+11 to R+8. ✅ Cook still rates it Solid Republican, and Trump carried the new lines by roughly 14 points. ✅ Neither party had a contested primary — both were cancelled at qualifying, so this matchup has been set since June 12. ⚠ Jennifer Jenkins reached this race only after two switches: she began the cycle running for U.S. Senate, moved to FL-6 against Randy Fine, then moved again to FL-8 after the map changed. Certified Aug 27, 2026.",
        candidates: [
          { name: "Mike Haridopolos (incumbent)", party: "R", winner: false,
            positions: ["Space Coast and NASA/commercial launch leadership", "Indian River Lagoon restoration and water quality", "Tax reform, veterans and border enforcement"],
            differentiators: ["Freshman U.S. Representative; former Florida Senate President", "Unopposed in the Aug 18 Republican primary, which was cancelled", "$1,197,777 cash on hand on $1.82M raised, as of July 29, 2026"],
            supporters: ["Delivers federal money and attention to the Space Coast's launch economy", "Co-chairs the Indian River Lagoon caucus — a locally salient environmental record", "Sits on a seat Trump still carried by roughly fourteen points"],
            opponents: ["A reliable party-line freshman with a thin independent legislative record [Verify — structural argument]", "The new Orange County territory is unfamiliar ground he has never represented", "Democrats argue an R+8 lean is within reach in a midterm backlash year [Verify — structural argument]"] },
          { name: "Jennifer Jenkins", party: "D", winner: false,
            positions: ["Affordability and cost of living", "Affordable health care and child care", "Opposition to what she calls MAGA extremism"],
            differentiators: ["Former Brevard County School Board member; speech-language pathologist", "Unopposed in the Aug 18 Democratic primary, which was cancelled", "$108,111 cash on hand on $725,731 raised, as of July 29, 2026", "⚠ Third district of the cycle: Senate, then FL-6, then FL-8"],
            supporters: ["Won a Brevard school board seat in heavily Republican territory, which shows crossover appeal", "Her campaign's July 2026 poll put her at 43–41 once voters heard her biography [Verify — a campaign-released internal poll]", "Ran nearly thirty points ahead among independents in that same internal survey [Verify — a campaign-released internal poll]"],
            opponents: ["The Florida Republican Party brands her 'Jumpin' Jenkins' over three race switches in one cycle", "Outraised better than two to one and holds roughly one eleventh of the incumbent's cash", "⚠ The same internal poll had her trailing 44–35 on a plain head-to-head ballot"] } ] } ] },
  9: { name: "U.S. House — FL District 9", region: "Osceola County and parts of Orange and Polk, running south through Indian River, Okeechobee, Highlands and Glades",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "THIS IS THE MOST REDRAWN SEAT IN FLORIDA: HB 1D DISMANTLED DARREN SOTO'S HISPANIC-MAJORITY OSCEOLA–ORANGE–POLK DISTRICT AND STRETCHED IT SOUTH through Indian River, Okeechobee, Highlands and Glades counties. ✅ Cook's PVI moved from D+4 to R+8 — a swing no other Florida district matched — and Trump would have carried the new lines about 58–41. ✅ Cook rates the race Likely Republican. ⚠ Soto had no primary opponent, but seven Republicans fought for the nomination and Dan Green won it with just 25.4%, meaning roughly three-quarters of Republican primary voters backed someone else. Certified Aug 27, 2026.",
        candidates: [
          { name: "Darren Soto (incumbent)", party: "D", winner: false,
            positions: ["Jobs and the economy; Social Security", "Health care access", "Environmental protection and Puerto Rico advocacy"],
            differentiators: ["U.S. Representative since 2017; former state senator", "Unopposed in the Aug 18 Democratic primary, which was cancelled", "$1,187,355 cash on hand on $2.16M raised, as of July 29, 2026", "First Floridian of Puerto Rican descent elected to Congress"],
            supporters: ["Nearly a decade of incumbency and deep roots in the Osceola County base", "Leads the field in money with more than $1.1M banked", "Long-standing advocacy for Puerto Rico resonates with Central Florida's Puerto Rican community"],
            opponents: ["Now runs in a seat Trump carried by roughly seventeen points", "The new southern rural counties are territory he has never represented", "Republicans argue his voting record is out of step with an R+8 electorate [Verify — structural argument]"] },
          { name: "Dan Green", party: "R", winner: false,
            positions: ["America First — affordability, grocery and gas prices", "Border security; supports the SAVE America Act", "Veterans and national defence"],
            differentiators: ["Navy Reserve commander, four Middle East tours; former Pentagon appointee", "Won the Aug 18 Republican primary with 25.38% — 14,748 votes", "$363,243 cash on hand on $1.30M raised, as of July 29, 2026", "Endorsed by Rep. Jim Jordan, Rep. Mike Haridopolos, Sen. Tim Sheehy and former Sen. Connie Mack"],
            supporters: ["Runs in a seat the new map made roughly twelve points more Republican", "A military and national-security resume fits a district with a large veteran population", "Consolidated national conservative endorsements ahead of the primary"],
            opponents: ["Won the nomination by only 587 votes with 25.4% in a seven-way field", "Has never held elected office", "Enters the general with under $400K against Soto's $1.19M"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "SEVEN REPUBLICANS SPLIT THE FIELD AND DAN GREEN WON WITH 25.38%, EDGING RANCHER BEN BUTLER BY 587 VOTES. ⚠ Thomas Chalifoux raised more than $3.1M — over twice Green's haul — and finished third. Darren Soto's Democratic primary was cancelled for lack of an opponent. Certified Aug 27, 2026.",
        candidates: [
          { name: "Dan Green", party: "R", winner: true, positions: [], differentiators: ["14,748 votes — 25.38% of 58,102 cast"], supporters: [], opponents: [] },
          { name: "Ben Butler", party: "R", winner: false, positions: [], differentiators: ["14,161 votes — 24.37%; lost by 587"], supporters: [], opponents: [] },
          { name: "Thomas E. Chalifoux Jr.", party: "R", winner: false, positions: [], differentiators: ["11,802 votes — 20.31%; raised $3,139,737, the most in the field, and finished third"], supporters: [], opponents: [] },
          { name: "Jorge Martinez", party: "R", winner: false, positions: [], differentiators: ["11,324 votes — 19.49%"], supporters: [], opponents: [] },
          { name: "Justin Story", party: "R", winner: false, positions: [], differentiators: ["2,484 votes — 4.28%"], supporters: [], opponents: [] },
          { name: "Marcus Carter", party: "R", winner: false, positions: [], differentiators: ["2,248 votes — 3.87%"], supporters: [], opponents: [] },
          { name: "Steve Rance", party: "R", winner: false, positions: [], differentiators: ["1,335 votes — 2.30%"], supporters: [], opponents: [] } ] } ] },
  10: { name: "U.S. House — FL District 10", region: "Most of Orlando, wholly inside Orange County",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "THERE IS NO NOVEMBER CONTEST HERE — MAXWELL FROST DREW NO OPPONENT AT ALL AND WAS RE-ELECTED WITHOUT APPEARING ON A BALLOT. ✅ When qualifying closed June 12, 2026, no Republican, minor-party or write-in candidate had qualified; both the Aug 18 primary and the Nov 3 general were cancelled and the seat does not appear on Orange County ballots. ✅ He is the only member of Florida's 28-seat delegation to win this cycle unopposed. ⚠ A Republican (Vibert White) and a write-in (Brent Lawhon) appear in the state database but the state says neither qualified. HB 1D shifted FL-10 west, shedding eastern Orange County, but left it wholly inside Orange and unchanged at Cook D+13 — Solid Democratic.",
        candidates: [
          { name: "Maxwell Alejandro Frost (incumbent)", party: "D", winner: false,
            positions: ["Gun violence prevention", "Federal constituent services and casework", "Support for federal workers facing layoffs and funding freezes"],
            differentiators: ["U.S. Representative since 2023; the first Gen Z member of Congress", "Re-elected unopposed at the June 12, 2026 qualifying deadline", "Former national organising director, March for Our Lives", "⚠ Both his primary and his general election were cancelled for lack of any opponent", "⚠ No FEC totals were retrievable for this seat [Verify]"],
            supporters: ["Won 62.4% in 2024 under the prior lines against a funded Republican", "A D+13 seat that HB 1D left essentially untouched", "No opponent from any party judged the seat worth contesting"],
            opponents: ["Running unopposed means voters get no contested choice and no head-to-head scrutiny this cycle [Verify — structural argument]", "No organised opposition campaign could be located in this district [Verify — an absence of located records]"] } ] } ] },
  11: { name: "U.S. House — FL District 11", region: "All of Sumter County including The Villages, plus parts of Lake and south-western Orange",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "OPEN SEAT — REP. DANIEL WEBSTER ANNOUNCED DURING THE REDISTRICTING SPECIAL SESSION THAT HE WOULD NOT SEEK RE-ELECTION. ✅ HB 1D shed the district's Polk County territory (about 41,000 residents) and pushed it deeper into south-western Orange; Cook's PVI barely moved, R+8 to R+7, and Cook rates it Solid Republican. ⚠ Republican nominee Joe Strada won by 393 votes out of 81,775 — a 0.48-point margin that triggered an AUTOMATIC MACHINE RECOUNT across Sumter, Lake and Orange counties. The recount, completed the weekend of Aug 22–24, confirmed the result, and the Elections Canvassing Commission certified on Aug 27.",
        candidates: [
          { name: "Joe Strada", party: "R", winner: false,
            positions: ["Immigration enforcement", "Government accountability and spending", "Closing the skilled-trades worker shortage through training programmes"],
            differentiators: ["Businessman who built trade-training programmes with his sons", "Won the Aug 18 Republican primary 33.49% to 33.01% — 393 votes, confirmed by machine recount", "$2,248,903 cash on hand on $5.25M raised, largely self-funded, as of July 29, 2026", "Endorsed by Rep. Jim Jordan and Polk County Sheriff Grady Judd"],
            supporters: ["Enters an R+7 open seat rated Solid Republican with more than $2.2M banked", "A workforce-training record gives him a concrete, non-ideological accomplishment to run on", "Consolidated Trump-aligned endorsements in a crowded five-way primary"],
            opponents: ["Won the nomination with under 34% and survived only after a recount", "Self-funding on this scale invites the charge that he bought the nomination [Verify — structural argument]", "⚠ As of Aug 28, 2026 his campaign site still showed only a 'Launching Soon' placeholder"] },
          { name: "James Pericola", party: "D", winner: false,
            positions: ["Protect Social Security and Medicare; protect the ACA", "Eliminate federal income tax below $100,000 and cut middle-class taxes", "End gerrymandering and pass the John Lewis Voting Rights Act"],
            differentiators: ["Attorney; Clinton administration presidential appointee and former congressional staffer", "Won the Aug 18 Democratic primary with 46.35% — 20,833 votes", "$32,231 cash on hand on $119,754 raised, as of July 29, 2026", "Campaigns on thirty-plus years of federal government-affairs experience"],
            supporters: ["Decades of Washington experience in an open-seat race against two first-time candidates", "An anti-gerrymandering message directly responsive to the map that redrew this district", "Won his primary outright without a recount, unlike his opponent"],
            opponents: ["Holds roughly $32K against Strada's $2.2M — a seventy-to-one cash gap", "Running in an R+7 seat Cook rates Solid Republican", "His long Washington resume cuts against the anti-insider mood he is appealing to [Verify — structural argument]"] },
          { name: "Ralph Groves", party: "L", winner: false,
            positions: ["Anti-war foreign policy paired with support for the U.S. defence industry", "Pro-legal-immigration and pro-Second Amendment", "Socially liberal, economically conservative constitutionalism"],
            differentiators: ["Recent Chairman, Libertarian Party of Orange County", "Retired Defense Intelligence Agency civilian analyst, 1999–2018", "Advanced from a cancelled Libertarian primary", "No FEC receipts on file as of July 29, 2026"],
            supporters: ["Offers voters an option in a district where the major-party race is rated Solid Republican", "Two decades of federal intelligence work behind his foreign-policy positions", "Publishes detailed position papers rather than slogans on his campaign site"],
            opponents: ["Unfunded against a self-funding nominee with $2.2M on hand [Verify — structural argument]", "Libertarian nominees in Florida U.S. House races have not been competitive for the seat [Verify — structural argument]", "No paid campaign presence in the district could be located [Verify — an absence of located records]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "JOE STRADA BEAT FORMER LAKE COUNTY PROPERTY APPRAISER CAREY BAKER BY 393 VOTES — 0.48 POINTS — TRIGGERING AN AUTOMATIC MACHINE RECOUNT ACROSS SUMTER, LAKE AND ORANGE COUNTIES. ✅ The recount, completed Aug 24, left the margin intact. ⚠ Retiring Rep. Daniel Webster and former state Rep. Anthony Sabatini both appear on the state's withdrawn / did-not-qualify list for this seat. Certified Aug 27, 2026.",
        candidates: [
          { name: "Joe Strada", party: "R", winner: true, positions: [], differentiators: ["27,389 votes — 33.49%; won by 393 after a machine recount"], supporters: [], opponents: [] },
          { name: "Carey Baker", party: "R", winner: false, positions: [], differentiators: ["26,996 votes — 33.01%", "Former Lake County Property Appraiser and state senator"], supporters: [], opponents: [] },
          { name: "Tim Wilkins", party: "R", winner: false, positions: [], differentiators: ["20,810 votes — 25.45%"], supporters: [], opponents: [] },
          { name: "Nizam Razack", party: "R", winner: false, positions: [], differentiators: ["4,742 votes — 5.80%; raised $932,552 and finished fourth"], supporters: [], opponents: [] },
          { name: "Ivette Palomo", party: "R", winner: false, positions: [], differentiators: ["1,838 votes — 2.25%"], supporters: [], opponents: [] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "JAMES PERICOLA TOOK 46.35% IN A THREE-WAY DEMOCRATIC PRIMARY. Certified Aug 27, 2026.",
        candidates: [
          { name: "James Pericola", party: "D", winner: true, positions: [], differentiators: ["20,833 votes — 46.35%"], supporters: [], opponents: [] },
          { name: "Royal Webster", party: "D", winner: false, positions: [], differentiators: ["12,356 votes — 27.49%"], supporters: [], opponents: [] },
          { name: "Dan Williams", party: "D", winner: false, positions: [], differentiators: ["11,759 votes — 26.16%"], supporters: [], opponents: [] } ] } ] },
  12: { name: "U.S. House — FL District 12", region: "Pasco County and northern Hillsborough County",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "FL-12 MOVED TEN POINTS TOWARD DEMOCRATS UNDER HB 1D — COOK'S PVI WENT FROM R+17 TO R+7, THE LARGEST DEMOCRATIC-DIRECTION SHIFT OF ANY FLORIDA DISTRICT. ✅ The map handed the district's northern Citrus, Hernando and Marion territory to the new District 15 and pushed FL-12 south into Hillsborough County. ⚠ Even so, Cook still rates the seat Solid Republican and Gus Bilirakis has held it since 2007. ⚠ Democratic nominee Kimberly Overman won her primary while being outraised nearly four to one and finished the pre-primary period with under $5,000 in the bank. Certified Aug 27, 2026.",
        candidates: [
          { name: "Gus M. Bilirakis (incumbent)", party: "R", winner: false,
            positions: ["Cut homeowners' insurance costs via the Homeowners Premium Tax Reduction Act", "Affordable housing and lowering the cost of living", "Veterans and seniors — the Major Richard Star Act, EASE Act telehealth, KidCare"],
            differentiators: ["U.S. Representative since 2007; chairs an Energy and Commerce subcommittee", "Unopposed in the Aug 18 Republican primary, which was cancelled", "$554,070 cash on hand on $1.59M raised, as of July 29, 2026"],
            supporters: ["A long record of district appropriations — $4M for Moffitt Cancer Center and about $6M for USF cancer research", "Property-insurance and telehealth work targets the top pocketbook complaints in Pasco and Hillsborough", "Holds a seat Cook still rates Solid Republican with a ten-to-one cash advantage"],
            opponents: ["Nearly two decades in office invites a career-politician critique [Verify — structural argument]", "The seat is ten points less safe than it was; a bad national environment could put it in play", "Democrats argue his party's health-care cuts undercut his seniors-focused message [Verify — structural argument]"] },
          { name: "Kimberly Overman", party: "D", winner: false,
            positions: ["Affordable housing, transit and child care as essential infrastructure", "Lower prescription costs; expand mental-health and reproductive care", "Public-education investment and workforce development"],
            differentiators: ["Former Hillsborough County Commissioner; retired financial adviser and small-business owner", "Won the Aug 18 Democratic primary with 52.66% — 21,833 votes", "$4,906 cash on hand on $186,813 raised, as of July 29, 2026", "Beat a rival who had raised nearly four times as much"],
            supporters: ["Won county-wide office in Hillsborough, the district's new southern anchor", "Beat a far better-funded primary opponent, which suggests organisational strength over money", "Runs in a district ten points more competitive than it was in 2024"],
            opponents: ["Ended the pre-primary period with under $5,000 against the incumbent's $554,000", "Cook rates the seat Solid Republican despite the shift", "Has never represented the Pasco County portion, which remains the district's population centre [Verify — structural argument]"] },
          { name: "Branden Scrivener", party: "I", winner: false,
            positions: ["⚠ Health care access, inferred from his stated occupation as a case manager — no platform document could be located [Verify]", "", ""],
            differentiators: ["Healthcare case manager; qualified with no party affiliation", "$353 cash on hand on $7,975 raised, as of June 30, 2026", "Appears on the November ballot as an NPA candidate"],
            supporters: ["Gives voters a non-partisan option in a seat where the major-party outcome is rated Solid Republican", "Front-line health-care work is directly relevant to a district with a large senior population"],
            opponents: ["Under $400 on hand against a $554,000 incumbent [Verify — structural argument]", "No organised campaign presence in the district could be located [Verify — an absence of located records]", "NPA candidates in Florida U.S. House races have not been competitive for the seat [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "KIMBERLY OVERMAN WON THE DEMOCRATIC NOMINATION 52.66% TO 47.34% DESPITE BEING OUTRAISED ALMOST FOUR TO ONE. ⚠ Darren McAuley raised $728,863 to Overman's $186,813 and lost by 2,207 votes. Gus Bilirakis had no Republican primary opponent. Certified Aug 27, 2026.",
        candidates: [
          { name: "Kimberly Overman", party: "D", winner: true, positions: [], differentiators: ["21,833 votes — 52.66% of 41,459 cast"], supporters: [], opponents: [] },
          { name: "Darren McAuley", party: "D", winner: false, positions: [], differentiators: ["19,626 votes — 47.34%; raised $728,863, the most in the primary, and lost"], supporters: [], opponents: [] } ] } ] },
  13: { name: "U.S. House — FL District 13", region: "Most of Pinellas County outside southern St. Petersburg — Clearwater and Largo — plus southern Pasco",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "HB 1D CUT SOUTHERN PINELLAS OUT OF FL-13 AND PUSHED IT NORTH INTO PASCO COUNTY, ADDING ABOUT 62,000 RESIDENTS. ✅ The net partisan effect was small — Cook's PVI moved only R+5 to R+6 — and Cook rates the race Likely Republican. ✅ Retired Army Brigadier General Leela Gray won the Democratic nomination outright with 65.01%, clearing a nine-candidate field that mostly withdrew before the ballot. ⚠ BOTH PUBLIC POLLS IN THIS RACE ARE CAMPAIGN INTERNALS POINTING OPPOSITE DIRECTIONS: Luna's pollster had her up 49–41, a Democratic internal had it 41–39. Treat both with caution. Certified Aug 27, 2026.",
        candidates: [
          { name: "Anna Paulina Luna (incumbent)", party: "R", winner: false,
            positions: ["Release of the Epstein files — she led the discharge petition [Verify — from her legislative record, not a 2026 campaign document]", "A congressional stock-trading ban and proxy voting for new parents [Verify — legislative record]", "Border enforcement and Republican tax cuts including no tax on tips [Verify — legislative record]"],
            differentiators: ["U.S. Representative since 2023, seeking a third term", "Unopposed in the Aug 18 Republican primary, which was cancelled", "$1,474,124 cash on hand on $3.23M raised, as of July 29, 2026", "⚠ No 2026 campaign website could be located — annapaulina.com is a parked domain listed for sale"],
            supporters: ["Out-raised every targeted Florida incumbent and holds $1.47M on hand", "Her Epstein-files and stock-trading-ban fights won cross-ideological attention", "Sits in a seat Cook rates Likely Republican that got marginally redder"],
            opponents: ["⚠ Her own pollster shows her under 50% against a first-time candidate", "A high-profile national profile draws the charge that she prioritises cable news over the district [Verify — structural argument]", "Democrats have targeted her since 2025 as one of Florida's most flippable Republicans"] },
          { name: "Leela Gray", party: "D", winner: false,
            positions: ["Lower housing, insurance, food and fuel costs", "Take on insurance monopolies driving up premiums", "Leadership over chaos — hurricane resilience and national security"],
            differentiators: ["Retired U.S. Army Brigadier General, thirty-five years' service; attorney and business leader", "Won the Aug 18 Democratic primary with 65.01% — 32,705 votes", "$683,295 cash on hand on $1.22M raised, as of July 29, 2026", "Endorsed by EMILY's List"],
            supporters: ["A one-star general's resume is unusually strong for a district with heavy veteran and MacDill-adjacent population", "Won her primary with two-thirds of the vote, avoiding a divisive fight", "Banked $683K — more than most challengers to Luna have ever raised"],
            opponents: ["Has never held elected office and faces a two-term incumbent with $1.47M", "Luna's internal poll put her down eight points", "The seat is R+6 and rated Likely Republican, which requires a substantial crossover vote [Verify — structural argument]"] },
          { name: "Tony D'Arrigo", party: "I", winner: false,
            positions: ["Reverse the $500B Medicare and $900B Medicaid cuts", "Guarantee real healthcare security for seniors and working families", "Hold congressional leadership accountable for programme cuts"],
            differentiators: ["Qualified with no party affiliation", "$25,681 cash on hand on $28,181 raised, as of June 30, 2026", "Runs a district-focused community organising effort"],
            supporters: ["A single-issue focus on Medicare and Medicaid cuts is highly salient in a Pinellas district with many seniors", "Has spent almost nothing of what he raised, keeping most of it available for the autumn", "Offers an option to voters unwilling to back either major party"],
            opponents: ["Roughly $26K on hand against a $1.47M incumbent [Verify — structural argument]", "An NPA campaign attacking Republicans mainly risks splitting the anti-Luna vote with Gray [Verify — structural argument]", "No polling shows him with measurable support [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Democratic primary",
        note: "LEELA GRAY WON THE DEMOCRATIC NOMINATION OUTRIGHT WITH 65.01%, MORE THAN DOUBLING HER NEAREST RIVAL. ⚠ Seven other Democrats had filed and withdrew before the ballot, leaving a three-way race. Anna Paulina Luna had no Republican primary opponent. Certified Aug 27, 2026.",
        candidates: [
          { name: "Leela Gray", party: "D", winner: true, positions: [], differentiators: ["32,705 votes — 65.01% of 50,311 cast"], supporters: [], opponents: [] },
          { name: "Brandt Robinson", party: "D", winner: false, positions: [], differentiators: ["13,279 votes — 26.39%"], supporters: [], opponents: [] },
          { name: "John William Liccione", party: "D", winner: false, positions: [], differentiators: ["4,327 votes — 8.60%"], supporters: [], opponents: [] } ] } ] },
  14: { name: "U.S. House — FL District 14", region: "Tampa and south-central Hillsborough County, entirely within Hillsborough",
    races: [
      { date: "Nov 3, 2026", type: "upcoming", scope: "Federal · District",
        note: "THE SINGLE MOST TRANSFORMED DISTRICT ON FLORIDA'S NEW MAP: HB 1D SEVERED FL-14'S CROSS-BAY LINK TO ST. PETERSBURG AND FLIPPED IT FROM COOK D+5 TO R+4 — AN 11.1-POINT RAW PVI SHIFT, THE LARGEST IN THE STATE. ✅ Harris carried the old lines 53.3–45.6; Trump would have carried the new lines 54.7–44.2. ✅ Kathy Castor, in office twenty years, is running anyway, and COOK NOW RATES THE SEAT TOSS UP. ⚠ Republican Mike Beltran finished the pre-primary period with MORE cash on hand than the incumbent. ⚠ Two write-in candidates, Salomon Hernandez and Keith Varian, are state-certified but do not appear on the printed ballot, so they are not carded here. Certified Aug 27, 2026.",
        candidates: [
          { name: "Kathy Castor (incumbent)", party: "D", winner: false,
            positions: ["Rein in housing costs and expand affordable housing", "Protect Tampa Bay's economic anchors — MacDill Air Force Base, Moffitt Cancer Center, USF", "Health care access and climate and environmental protection"],
            differentiators: ["U.S. Representative since 2007; senior member, House Energy and Commerce Committee", "Unopposed in the Aug 18 Democratic primary, which was cancelled", "$1,744,723 cash on hand on $2.34M raised, as of July 29, 2026", "Endorsed by EMILY's List, the Florida AFL-CIO, AFGE, Planned Parenthood Action Fund, LCV Action Fund and Sierra Club Independent Action"],
            supporters: ["Led 46–38 in the only independent public poll of the race (St. Pete Polls for Florida Politics, July 14–15, 2026, 469 likely voters, ±4.5%)", "Two decades of federal appropriations for Tampa institutions give her a concrete local record", "Assembled the broadest labour and environmental endorsement slate in the race"],
            opponents: ["Now runs in a seat Trump would have carried by more than ten points", "Beltran's attack that twenty years in Congress made her wealthy while costs rose is the core Republican message", "Ended the pre-primary period with less cash on hand than her challenger"] },
          { name: "Mike Beltran", party: "R", winner: false,
            positions: ["Lower health care costs and expand access — telehealth, fewer clinic barriers", "Cut the cost of living and federal spending; tax relief", "Require local approval before any data centre is built in Hillsborough County"],
            differentiators: ["Six years in the Florida House; Harvard Law graduate and attorney", "Won the Aug 18 Republican primary with 45.59% — 25,866 votes — over seven rivals", "$1,939,864 cash on hand — MORE than the incumbent — as of July 29, 2026", "Endorsed by Reps. Gus Bilirakis and Greg Steube, AIPAC, the Freedom Caucus Fund, Gun Owners of America and the Republican Liberty Caucus"],
            supporters: ["Runs on lines that now lean Republican by four points on Cook's PVI", "Out-banked a twenty-year incumbent, spending only $177K of $2.1M raised through the primary", "His data-centre consent plank is a locally specific issue neither party had claimed"],
            opponents: ["Trailed by eight points in the only independent public poll of the race", "Won his primary with under 46% in an eight-way field", "Gun Owners of America and Freedom Caucus Fund backing gives Democrats a line of attack in a Tampa electorate [Verify — structural argument]"] },
          { name: "Brian Lambert", party: "L", winner: false,
            positions: ["Restore constitutional limits on federal government", "Protect individual liberty across left-right lines", "Trust Americans over Washington institutions"],
            differentiators: ["Twenty-year U.S. Navy veteran", "Advanced from a cancelled Libertarian primary", "$100 cash on hand on $10,500 raised, as of June 30, 2026", "Runs a full published issues platform"],
            supporters: ["Offers a third option in a genuine toss-up where both major parties are running national messages", "A military service record in a district that includes MacDill Air Force Base personnel", "Maintains a substantive published platform rather than a placeholder site"],
            opponents: ["$100 on hand against two candidates with roughly $1.8M each [Verify — structural argument]", "In a toss-up seat, a Libertarian vote is likely to be argued as a spoiler [Verify — structural argument]", "No polling shows him with measurable support [Verify — structural argument]"] } ] },
      { date: "Aug 18, 2026", type: "past", scope: "Federal · District · Republican primary",
        note: "MIKE BELTRAN WON A CROWDED EIGHT-WAY REPUBLICAN PRIMARY WITH 45.59%, BEATING KEVIN STEELE BY MORE THAN FIFTEEN POINTS. ⚠ Steele raised and spent more than Beltran — $2.59M raised, $2.11M spent — and finished second. ✅ Beltran spent only about $177,000 of the $2.1M he raised, carrying $1.94M into the general. Kathy Castor had no Democratic primary opponent. Certified Aug 27, 2026.",
        candidates: [
          { name: "Mike Beltran", party: "R", winner: true, positions: [], differentiators: ["25,866 votes — 45.59% of 56,734 cast"], supporters: [], opponents: [] },
          { name: "Kevin M. Steele", party: "R", winner: false, positions: [], differentiators: ["17,140 votes — 30.21%; raised $2,588,952 and spent $2,106,349, the most in the field"], supporters: [], opponents: [] },
          { name: "Bea Valenti", party: "R", winner: false, positions: [], differentiators: ["5,430 votes — 9.57%"], supporters: [], opponents: [] },
          { name: "Robert 'Rocky' Rochford", party: "R", winner: false, positions: [], differentiators: ["4,046 votes — 7.13%"], supporters: [], opponents: [] },
          { name: "John Peters", party: "R", winner: false, positions: [], differentiators: ["1,573 votes — 2.77%; raised $203,332 and spent all of it"], supporters: [], opponents: [] },
          { name: "Michael Marcel", party: "R", winner: false, positions: [], differentiators: ["1,016 votes — 1.79%"], supporters: [], opponents: [] },
          { name: "Ergin 'Batman' Tek", party: "R", winner: false, positions: [], differentiators: ["970 votes — 1.71%"], supporters: [], opponents: [] },
          { name: "Gavriel E. Soriano", party: "R", winner: false, positions: [], differentiators: ["693 votes — 1.22%"], supporters: [], opponents: [] } ] } ] },
